# Generated by Django 5.0.11 on 2026-02-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("EHS", "0003_lagging_indicator_contractor_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pssrobservation",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
    ]
