# Generated by Django 5.0.11 on 2026-03-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("EHS", "0004_pssrobservation_remark"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dailyworkpermit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("permit_date", models.DateField(blank=True, null=True)),
                ("site_time", models.TimeField()),
                ("permit_approval_time", models.TimeField()),
                ("reason_for_delay", models.TextField(blank=True, null=True)),
                ("work_description", models.TextField()),
                ("work_location", models.CharField(max_length=200)),
                ("permit_no", models.IntegerField()),
                (
                    "work_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Height Work", "Height Work"),
                            ("Hot Work", "Hot Work"),
                            ("Confined Space", "Confined Space"),
                            ("Tanker Loading", "Tanker Loading"),
                            ("Excavation", "Excavation"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "work_type_value",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("initiated_by", models.CharField(max_length=100)),
                (
                    "permit_open_closed",
                    models.CharField(
                        choices=[("Open", "Open"), ("Closed", "Closed")], max_length=20
                    ),
                ),
                ("permit_status_reason", models.TextField(blank=True, null=True)),
                ("valid_from", models.TimeField(blank=True, null=True)),
                ("valid_to", models.TimeField(blank=True, null=True)),
                ("Extenction_valid_from", models.TimeField(blank=True, null=True)),
                ("Extenction_valid_to", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "daily_work_permit",
            },
        ),
    ]
