# Generated by Django 5.0.11 on 2025-09-26 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HRContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField(db_column="work_date")),
                (
                    "in_date",
                    models.DateField(blank=True, db_column="in_date", null=True),
                ),
                (
                    "in_time",
                    models.TimeField(blank=True, db_column="in_time", null=True),
                ),
                (
                    "out_date",
                    models.DateField(blank=True, db_column="out_date", null=True),
                ),
                (
                    "out_time",
                    models.TimeField(blank=True, db_column="out_time", null=True),
                ),
                ("shift", models.CharField(db_column="shift", max_length=50)),
                (
                    "work_hhmm",
                    models.CharField(
                        blank=True, db_column="work_hhmm", max_length=10, null=True
                    ),
                ),
                (
                    "ot_hours",
                    models.DecimalField(
                        blank=True,
                        db_column="ot_hours",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "double_ot_hours",
                    models.DecimalField(
                        blank=True,
                        db_column="double_ot_hours",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "block",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A Block", "A Block"),
                            ("B Block", "B Block"),
                            ("C Block", "C Block"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "hr_contract",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ContractEmpDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "contract_employee_dept",
            },
        ),
        migrations.CreateModel(
            name="ContractorName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "contract_name",
            },
        ),
        migrations.CreateModel(
            name="ContractEmployee",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("employee_type", models.CharField(max_length=50)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="CONTRACT.contractempdepartment",
                    ),
                ),
            ],
            options={
                "db_table": "contract_employee",
            },
        ),
        migrations.CreateModel(
            name="EmployeeAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("punch_date", models.DateField()),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ACCOUNTS", "ACCOUNTS"),
                            ("BOILER", "BOILER"),
                            ("UTILITY", "UTILITY"),
                            ("ELECTRICAL", "ELECTRICAL"),
                            ("EHS", "EHS"),
                            ("HR ADMIN", "HR ADMIN"),
                            ("INSTRUMENT", "INSTRUMENT"),
                            ("IT", "IT"),
                            ("MAINTENANCE", "MAINTENANCE"),
                            ("OPERATION", "OPERATION"),
                            ("PRODUCTION", "PRODUCTION"),
                            ("QA/QC", "QA/QC"),
                            ("SECURITY", "SECURITY"),
                            ("STORE", "STORE"),
                            ("ETP", "ETP"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "block_location",
                    models.CharField(
                        choices=[
                            ("A Block", "A Block"),
                            ("B Block", "B Block"),
                            ("C Block", "C Block"),
                            ("D Block", "D Block"),
                            ("E Block", "E Block"),
                            ("Boiler", "Boiler"),
                            ("Dozer Driver", "Dozer Driver"),
                            ("E Block- 17 Production", "E Block- 17 Production"),
                            ("Gardenar", "Gardenar"),
                            ("MEE/ETP", "MEE/ETP"),
                            ("MNTS", "MNTS"),
                            ("Painting", "Painting"),
                            ("PKG", "PKG"),
                            ("QC & PD", "QC & PD"),
                            ("RM/ENGG 16 - 17 & 18", "RM/ENGG 16 - 17 & 18"),
                            ("RO Plant", "RO Plant"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "1st Shift (07:00AM-15:00PM)",
                                "1st Shift (07:00AM-15:00PM)",
                            ),
                            ("General (09:00AM-18:00PM)", "General (09:00AM-18:00PM)"),
                            (
                                "2nd Shift (15:00PM-23:00PM)",
                                "2nd Shift (15:00PM-23:00PM)",
                            ),
                            (
                                "4th Shift (19:00PM-07:00AM)",
                                "4th Shift (19:00PM-07:00AM)",
                            ),
                            ("Night (23:00PM-07:00AM)", "Night (23:00PM-07:00AM)"),
                            (
                                "3rd Shift (07:00AM-19:00PM)",
                                "3rd Shift (07:00AM-19:00PM)",
                            ),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("punch_in", models.TimeField(blank=True, null=True)),
                ("punch_out", models.TimeField(blank=True, null=True)),
                ("assigned_date", models.DateTimeField(auto_now_add=True)),
                (
                    "contractor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="CONTRACT.contractorname",
                        verbose_name="Contractor Name",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="CONTRACT.contractemployee",
                    ),
                ),
            ],
            options={
                "db_table": "contract_employee_assignment",
            },
        ),
    ]
