# Generated by Django 5.0.11 on 2025-09-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CONTRACT", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeassignment",
            name="is_reassigned",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="employeeassignment",
            name="block_location",
            field=models.CharField(
                choices=[
                    ("A Block", "A Block"),
                    ("B Block", "B Block"),
                    ("C Block", "C Block"),
                    ("D Block", "D Block"),
                    ("E Block", "E Block"),
                    ("PKG", "PKG"),
                    ("Pilot", "Pilot"),
                    ("E Block- 17 Production", "E Block- 17 Production"),
                    ("MEE/ETP", "MEE/ETP"),
                    ("MNTS", "MNTS"),
                    ("PKG", "PKG"),
                    ("QC & PD", "QC & PD"),
                    ("RO Plant", "RO Plant"),
                    ("ELE", "ELE"),
                    ("INST", "INST"),
                    ("RM/ENGG 16 - 17 & 18", "RM/ENGG 16 - 17 & 18"),
                    ("Boiler", "Boiler"),
                    ("Dozer Driver", "Dozer Driver"),
                    ("HouseKeeping 16 - 17 & 18", "HouseKeeping 16 - 17 & 18"),
                    ("Office Boy", "Office Boy"),
                    ("Gardenar", "Gardenar"),
                    ("OHC", "OHC"),
                    ("Painting", "Painting"),
                    ("MNTS-E 17", "MNTS-E 17"),
                    ("ELE-E 17", "ELE-E 17"),
                    ("INST-E 17", "INST-E 17"),
                ],
                max_length=100,
            ),
        ),
    ]
