# Generated by Django 5.0.11 on 2025-11-04 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("STORE", "0004_alter_vehicle_qty"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("zone", models.CharField(blank=True, max_length=30)),
                ("row", models.CharField(blank=True, max_length=30)),
                ("level", models.CharField(blank=True, max_length=30)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "store_rack",
            },
        ),
        migrations.CreateModel(
            name="GrnLineCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField()),
                ("year_id", models.IntegerField()),
                ("doc_no", models.CharField(db_index=True, max_length=50)),
                ("doc_date", models.DateField(db_index=True)),
                ("supplier_code", models.CharField(blank=True, max_length=30)),
                ("supplier_name", models.CharField(blank=True, max_length=200)),
                ("item_code", models.CharField(db_index=True, max_length=50)),
                ("item_name", models.CharField(blank=True, max_length=300)),
                ("pr_item_type", models.CharField(blank=True, max_length=100)),
                ("batch_no", models.CharField(blank=True, max_length=80)),
                ("uom", models.CharField(blank=True, max_length=20)),
                ("qty", models.DecimalField(decimal_places=3, max_digits=18)),
                ("rm_pm", models.CharField(db_index=True, default="RM", max_length=2)),
                ("warehouse", models.CharField(blank=True, max_length=50)),
                ("erp_line_id", models.CharField(max_length=80, unique=True)),
            ],
            options={
                "db_table": "store_grn_line_cache",
                "indexes": [
                    models.Index(
                        fields=["doc_date"], name="store_grn_l_doc_dat_a16f72_idx"
                    ),
                    models.Index(
                        fields=["item_code"], name="store_grn_l_item_co_4991f9_idx"
                    ),
                    models.Index(fields=["rm_pm"], name="store_grn_l_rm_pm_d1441a_idx"),
                    models.Index(
                        fields=["pr_item_type"], name="store_grn_l_pr_item_e9e09c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IssueLineCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_id", models.IntegerField()),
                ("year_id", models.IntegerField()),
                ("issue_no", models.CharField(db_index=True, max_length=50)),
                ("issue_date", models.DateField(db_index=True)),
                ("cost_center", models.CharField(blank=True, max_length=120)),
                ("item_code", models.CharField(db_index=True, max_length=50)),
                ("item_name", models.CharField(blank=True, max_length=300)),
                ("issue_item_type", models.CharField(blank=True, max_length=100)),
                ("batch_no", models.CharField(blank=True, max_length=80)),
                ("uom", models.CharField(blank=True, max_length=20)),
                ("qty", models.DecimalField(decimal_places=3, max_digits=18)),
                ("warehouse", models.CharField(blank=True, max_length=50)),
                ("erp_line_id", models.CharField(max_length=80, unique=True)),
            ],
            options={
                "db_table": "store_issue_line_cache",
                "indexes": [
                    models.Index(
                        fields=["issue_date"], name="store_issue_issue_d_80a355_idx"
                    ),
                    models.Index(
                        fields=["item_code"], name="store_issue_item_co_95996e_idx"
                    ),
                    models.Index(
                        fields=["issue_item_type"],
                        name="store_issue_issue_i_1c2e48_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Pallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pallets",
                        to="STORE.rack",
                    ),
                ),
            ],
            options={
                "db_table": "store_pallet",
            },
        ),
        migrations.CreateModel(
            name="RackAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allocated_qty", models.DecimalField(decimal_places=3, max_digits=18)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "grn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="STORE.grnlinecache",
                    ),
                ),
                (
                    "pallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="STORE.pallet",
                    ),
                ),
                (
                    "rack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="STORE.rack"
                    ),
                ),
            ],
            options={
                "db_table": "store_rack_allocation",
            },
        ),
        migrations.CreateModel(
            name="RackIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.DecimalField(decimal_places=3, max_digits=18)),
                (
                    "allocation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consumptions",
                        to="STORE.rackallocation",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rack_breakups",
                        to="STORE.issuelinecache",
                    ),
                ),
            ],
            options={
                "db_table": "store_rack_issue",
            },
        ),
        migrations.AddConstraint(
            model_name="pallet",
            constraint=models.UniqueConstraint(
                fields=("rack", "number"), name="uq_store_pallet_rack_number"
            ),
        ),
    ]
