# Generated by Django 5.0.11 on 2026-02-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("STORE", "0005_rack_grnlinecache_issuelinecache_pallet_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvAgeingPreview",
            fields=[
                (
                    "invageingpreviewid",
                    models.BigAutoField(
                        db_column="InvAgeingPreviewId",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.IntegerField(db_column="company_id")),
                ("doc_no", models.CharField(db_column="doc_no", max_length=50)),
                ("doc_date", models.DateField(db_column="doc_date")),
                (
                    "company_name",
                    models.CharField(db_column="company_name", max_length=200),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        blank=True,
                        db_column="transaction_type",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        blank=True, db_column="item_type", max_length=100, null=True
                    ),
                ),
                (
                    "item_code",
                    models.CharField(
                        blank=True, db_column="item_code", max_length=60, null=True
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        blank=True, db_column="item_name", max_length=255, null=True
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, db_column="unit", max_length=60, null=True
                    ),
                ),
                (
                    "from_location",
                    models.CharField(
                        blank=True, db_column="from_location", max_length=200, null=True
                    ),
                ),
                (
                    "from_project",
                    models.CharField(
                        blank=True, db_column="from_project", max_length=200, null=True
                    ),
                ),
                (
                    "to_location",
                    models.CharField(
                        blank=True, db_column="to_location", max_length=200, null=True
                    ),
                ),
                (
                    "to_project",
                    models.CharField(
                        blank=True, db_column="to_project", max_length=200, null=True
                    ),
                ),
                (
                    "txn_location",
                    models.CharField(
                        blank=True, db_column="txn_location", max_length=200, null=True
                    ),
                ),
                (
                    "stock_location",
                    models.CharField(
                        blank=True,
                        db_column="stock_location",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "batch_no",
                    models.CharField(
                        blank=True, db_column="batch_no", max_length=120, null=True
                    ),
                ),
                (
                    "mfg_date",
                    models.DateField(blank=True, db_column="mfg_date", null=True),
                ),
                (
                    "retest_date",
                    models.DateField(blank=True, db_column="retest_date", null=True),
                ),
                (
                    "opening_qty",
                    models.DecimalField(
                        db_column="opening_qty", decimal_places=3, max_digits=21
                    ),
                ),
                (
                    "receipt_qty",
                    models.DecimalField(
                        db_column="receipt_qty", decimal_places=3, max_digits=21
                    ),
                ),
                (
                    "issue_qty",
                    models.DecimalField(
                        db_column="issue_qty", decimal_places=3, max_digits=21
                    ),
                ),
                (
                    "closing_qty",
                    models.DecimalField(
                        db_column="closing_qty", decimal_places=3, max_digits=21
                    ),
                ),
                (
                    "closing_value",
                    models.DecimalField(
                        db_column="closing_value", decimal_places=3, max_digits=21
                    ),
                ),
                (
                    "inventory_category",
                    models.CharField(
                        blank=True,
                        db_column="inventory_category",
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "inventory_subcategory",
                    models.CharField(
                        blank=True,
                        db_column="inventory_subcategory",
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "row_in_batch",
                    models.IntegerField(
                        blank=True, db_column="row_in_batch", null=True
                    ),
                ),
                (
                    "total_closing_per_batch",
                    models.DecimalField(
                        blank=True,
                        db_column="total_closing_per_batch",
                        decimal_places=3,
                        max_digits=21,
                        null=True,
                    ),
                ),
                (
                    "total_closing_value_per_batch",
                    models.DecimalField(
                        blank=True,
                        db_column="total_closing_value_per_batch",
                        decimal_places=3,
                        max_digits=21,
                        null=True,
                    ),
                ),
                (
                    "sum_closing_qty",
                    models.DecimalField(
                        blank=True,
                        db_column="sum_closing_qty",
                        decimal_places=3,
                        max_digits=21,
                        null=True,
                    ),
                ),
                (
                    "sum_closing_value",
                    models.DecimalField(
                        blank=True,
                        db_column="sum_closing_value",
                        decimal_places=3,
                        max_digits=21,
                        null=True,
                    ),
                ),
                (
                    "batch_start_date",
                    models.DateField(
                        blank=True, db_column="batch_start_date", null=True
                    ),
                ),
                (
                    "age_days",
                    models.IntegerField(blank=True, db_column="age_days", null=True),
                ),
                ("synced_at", models.DateTimeField(db_column="synced_at")),
            ],
            options={
                "verbose_name": "Inventory Ageing Preview",
                "verbose_name_plural": "Inventory Ageing Preview",
                "db_table": "InvAgeingPreview",
                "permissions": [
                    ("sync_invageingpreview", "Can sync Inventory Ageing Preview")
                ],
                "managed": False,
            },
        ),
    ]
