# Generated by Django 5.0.11 on 2025-12-04 05:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalCareMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("subcategory", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Personal Care Master",
                "verbose_name_plural": "Personal Care Master",
                "db_table": "personal_care_master",
            },
        ),
        migrations.CreateModel(
            name="PC_SampleRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inquiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Inquiry Date (dd-mm-yy)"
                    ),
                ),
                (
                    "sample_dispatch_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Sample Dispatch Date (Project Start Date)",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Year (from Sample Dispatch Date)",
                    ),
                ),
                (
                    "project_close_date",
                    models.DateField(
                        blank=True,
                        help_text="Store as any date within the closing month",
                        null=True,
                        verbose_name="Project Close Date (mm-yy)",
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REPLACEMENT", "Replacement"),
                            ("NPD", "NPD"),
                            ("PROTOTYPE", "Prototype"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Project Type",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("contact_no", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "sample_quantity",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Sample Quantity (in gm/ml)"
                    ),
                ),
                (
                    "price_indication_given",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Price Indication Given",
                    ),
                ),
                (
                    "followup_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last Follow-up Date"
                    ),
                ),
                (
                    "approval_by_nmp",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YES", "Yes"),
                            ("NO", "No"),
                            ("DONE", "Done"),
                            ("HOLD", "Hold"),
                            ("PENDING", "Pending"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Approval By NMP",
                    ),
                ),
                (
                    "approved_quantity",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Approved Quantity"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer_name",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Customer Name"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_customer_name",
                        to="PERSONAL_CARE.personalcaremaster",
                    ),
                ),
                (
                    "executive_name",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Executive Name"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_executive_name",
                        to="PERSONAL_CARE.personalcaremaster",
                    ),
                ),
                (
                    "product_name",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Product Name"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_product_name",
                        to="PERSONAL_CARE.personalcaremaster",
                    ),
                ),
                (
                    "project_name",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Project Name"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_project_name",
                        to="PERSONAL_CARE.personalcaremaster",
                    ),
                ),
                (
                    "remarks_master",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Remarks"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_remarks",
                        to="PERSONAL_CARE.personalcaremaster",
                        verbose_name="Remarks (master)",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Stage"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_stage",
                        to="PERSONAL_CARE.personalcaremaster",
                    ),
                ),
                (
                    "supplier_name",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Supplier Name"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_supplier_name",
                        to="PERSONAL_CARE.personalcaremaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "PC Sample Request",
                "verbose_name_plural": "PC Sample Requests",
                "db_table": "pc_sample_request",
            },
        ),
        migrations.CreateModel(
            name="PC_Executive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pc_executive",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "executive",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Executive Name"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pc_executive_links",
                        to="PERSONAL_CARE.personalcaremaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "PC Executive",
                "verbose_name_plural": "PC Executives",
                "db_table": "pc_executive",
            },
        ),
        migrations.CreateModel(
            name="PC_CustomerMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Created date",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("contact_no", models.CharField(blank=True, max_length=150, null=True)),
                ("email_id", models.CharField(blank=True, max_length=355, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "followup_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Follow-up date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(
                        auto_now=True, null=True, verbose_name="Updated date"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "City"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="City_customers",
                        to="PERSONAL_CARE.personalcaremaster",
                    ),
                ),
                (
                    "customer_name",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Customer Name"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_Name",
                        to="PERSONAL_CARE.personalcaremaster",
                    ),
                ),
                (
                    "customer_profile",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Customer Profile"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_profile_customers",
                        to="PERSONAL_CARE.personalcaremaster",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Designation"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="designation_customers",
                        to="PERSONAL_CARE.personalcaremaster",
                    ),
                ),
                (
                    "executive_name",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Executive Name"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Executive_Name",
                        to="PERSONAL_CARE.personalcaremaster",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Place"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Place_customers",
                        to="PERSONAL_CARE.personalcaremaster",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Source"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Source",
                        to="PERSONAL_CARE.personalcaremaster",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "State"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="State_customers",
                        to="PERSONAL_CARE.personalcaremaster",
                    ),
                ),
                (
                    "sub_profile",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Sub Profile"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_profile_customers",
                        to="PERSONAL_CARE.personalcaremaster",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Zone"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Zone_customers",
                        to="PERSONAL_CARE.personalcaremaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Personal Care Customer",
                "verbose_name_plural": "Customers",
                "db_table": "pc_customer_master",
            },
        ),
    ]
