# Generated by Django 5.0.11 on 2025-12-09 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PERSONAL_CARE", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer_Followup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode_of_followup",
                    models.CharField(
                        choices=[
                            ("In-Person Visit", "In-Person Visit"),
                            ("Email", "Email"),
                            ("Phone Call", "Phone Call"),
                        ],
                        max_length=100,
                        verbose_name="Mode of Follow-up",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="Date")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_followups_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer_name",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Customer Name"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_followups_customer",
                        to="PERSONAL_CARE.personalcaremaster",
                        verbose_name="Customer Name",
                    ),
                ),
                (
                    "executive_name",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Executive Name"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_followups_executive",
                        to="PERSONAL_CARE.personalcaremaster",
                        verbose_name="Executive Name",
                    ),
                ),
                (
                    "followup_status",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Followup Status"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="followup_status",
                        to="PERSONAL_CARE.personalcaremaster",
                        verbose_name="Followup Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Follow-up",
                "verbose_name_plural": "Customer Follow-ups",
                "db_table": "customer_followup",
            },
        ),
    ]
