# Generated by Django 5.0.11 on 2025-12-09 12:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("PERSONAL_CARE", "0002_customer_followup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pc_customermaster",
            name="followup_date",
        ),
    ]
