# Generated by Django 5.0.11 on 2025-12-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PERSONAL_CARE", "0003_remove_pc_customermaster_followup_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pc_samplerequest",
            name="approval_by_nmp",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Approved", "Approved"),
                    ("Pending", "Pending"),
                    ("Hold", "Hold"),
                ],
                default="Pending",
                max_length=10,
                null=True,
                verbose_name="Approval By NMP",
            ),
        ),
    ]
