# Generated by Django 5.0.11 on 2025-12-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PERSONAL_CARE", "0004_alter_pc_samplerequest_approval_by_nmp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pc_samplerequest",
            name="followup_date",
            field=models.DateField(
                blank=True,
                help_text="Only month & year are used; stored as 1st day of that month.",
                null=True,
                verbose_name="Last Follow-up Month",
            ),
        ),
    ]
