# Generated by Django 5.0.11 on 2025-12-25 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PERSONAL_CARE", "0005_alter_pc_samplerequest_followup_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer_followup",
            name="customer_profile",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category": "Sub Profile"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_profile",
                to="PERSONAL_CARE.personalcaremaster",
                verbose_name="Customer Profile",
            ),
        ),
    ]
