# Generated by Django 5.0.11 on 2026-01-08 06:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PERSONAL_CARE", "0006_customer_followup_customer_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="PC_Other_CustomerMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Created date",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("contact_no", models.CharField(blank=True, max_length=150, null=True)),
                ("email_id", models.CharField(blank=True, max_length=355, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "updated_at",
                    models.DateField(
                        auto_now=True, null=True, verbose_name="Updated date"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "City"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="City_customers_other",
                        to="PERSONAL_CARE.personalcaremaster",
                    ),
                ),
                (
                    "customer_name",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Customer Name"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Other_customer_Name",
                        to="PERSONAL_CARE.personalcaremaster",
                    ),
                ),
                (
                    "customer_profile",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Customer Profile"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_profile_customers_other",
                        to="PERSONAL_CARE.personalcaremaster",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Designation"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="designation_customers_other",
                        to="PERSONAL_CARE.personalcaremaster",
                    ),
                ),
                (
                    "executive_name",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Executive Name"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Executive_Name_other",
                        to="PERSONAL_CARE.personalcaremaster",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Place"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Place_customers_other",
                        to="PERSONAL_CARE.personalcaremaster",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Source"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Source_other",
                        to="PERSONAL_CARE.personalcaremaster",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "State"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="State_customers_other",
                        to="PERSONAL_CARE.personalcaremaster",
                    ),
                ),
                (
                    "sub_profile",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Sub Profile"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_profile_customers_other",
                        to="PERSONAL_CARE.personalcaremaster",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "Zone"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Zone_customers_other",
                        to="PERSONAL_CARE.personalcaremaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Personal Care Other Customer",
                "verbose_name_plural": "Others Customers",
                "db_table": "pc_other_customer_master",
            },
        ),
    ]
