# Generated by Django 5.0.11 on 2026-01-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PERSONAL_CARE", "0007_pc_other_customermaster"),
    ]

    operations = [
        migrations.AddField(
            model_name="pc_other_customermaster",
            name="core_business",
            field=models.TextField(blank=True, null=True),
        ),
    ]
