# Generated by Django 5.0.11 on 2026-03-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PERSONAL_CARE", "0008_pc_other_customermaster_core_business"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pc_samplerequest",
            options={
                "permissions": [
                    ("can_approve_sample_request", "can_approve_sample_request")
                ],
                "verbose_name": "PC Sample Request",
                "verbose_name_plural": "PC Sample Requests",
            },
        ),
        migrations.AlterField(
            model_name="customer_followup",
            name="mode_of_followup",
            field=models.CharField(
                choices=[
                    ("In-Person Visit", "In-Person Visit"),
                    ("Email", "Email"),
                    ("Phone Call", "Phone Call"),
                    ("No Follow-up", "No Follow-up"),
                ],
                max_length=100,
                verbose_name="Mode of Follow-up",
            ),
        ),
    ]
