# Generated by Django 5.0.11 on 2025-12-29 17:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutgoingEmailAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_group",
                    models.CharField(db_index=True, default="ALL", max_length=40),
                ),
                ("from_email", models.EmailField(max_length=254)),
                (
                    "from_name",
                    models.CharField(
                        blank=True, default="Accounts Team", max_length=120
                    ),
                ),
                ("use_custom_smtp", models.BooleanField(default=False)),
                ("host", models.CharField(blank=True, default="", max_length=200)),
                ("port", models.IntegerField(blank=True, null=True)),
                ("username", models.CharField(blank=True, default="", max_length=200)),
                ("password", models.CharField(blank=True, default="", max_length=200)),
                ("use_tls", models.BooleanField(default=True)),
                ("use_ssl", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "ACCOUNTS_outgoingemailaccount",
            },
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "party_code",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("party_name", models.CharField(db_index=True, max_length=255)),
                ("gst_no", models.CharField(blank=True, default="", max_length=30)),
                ("address", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "ACCOUNTS_party",
            },
        ),
        migrations.CreateModel(
            name="PartyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "designation",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("mobile", models.CharField(blank=True, default="", max_length=30)),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("is_primary", models.BooleanField(default=False)),
                ("receive_pdc_reminder", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "ACCOUNTS_partycontact",
            },
        ),
        migrations.CreateModel(
            name="PaymentTargetLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("party_code", models.CharField(db_index=True, max_length=50)),
                ("party_name", models.CharField(db_index=True, max_length=255)),
                ("invoice_no", models.CharField(blank=True, default="", max_length=80)),
                (
                    "invoice_date",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("due_date", models.CharField(blank=True, default="", max_length=50)),
                (
                    "bill_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "outstanding_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "expected_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("promised_date", models.DateField(blank=True, null=True)),
                ("discussion_notes", models.TextField(blank=True, default="")),
                (
                    "followup_owner",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("Part Received", "Part Received"),
                            ("Received", "Received"),
                            ("Deferred", "Deferred"),
                        ],
                        default="Open",
                        max_length=30,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "db_table": "ACCOUNTS_paymenttargetline",
            },
        ),
        migrations.CreateModel(
            name="PaymentTargetWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField(db_index=True)),
                ("week_end", models.DateField(db_index=True)),
                (
                    "company_group",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "ACCOUNTS_paymenttargetweek",
                "ordering": ["-week_start", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PDCReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reminder_date", models.DateField(db_index=True)),
                ("sent_to", models.TextField(blank=True, default="")),
                ("subject", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("Sent", "Sent"), ("Failed", "Failed")],
                        default="Sent",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ACCOUNTS_pdcreminderlog",
            },
        ),
        migrations.CreateModel(
            name="Receivable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_code", models.CharField(blank=True, max_length=30)),
                ("customer_name", models.CharField(max_length=255)),
                ("invoice_number", models.CharField(max_length=50)),
                ("invoice_date", models.DateField()),
                ("due_date", models.DateField()),
                ("currency", models.CharField(default="INR", max_length=10)),
                (
                    "invoice_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "received_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("cheque_no", models.CharField(blank=True, max_length=50, null=True)),
                ("cheque_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("PARTIAL", "Partially Received"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("days_overdue", models.IntegerField(default=0)),
                ("aging_bucket", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ACCOUNTS_receivable",
                "ordering": ["-invoice_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ReceivableSnapshotRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField(db_index=True)),
                (
                    "erp_lid",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "erp_acc_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "erp_comp_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "erp_typ_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "party_code",
                    models.CharField(blank=True, db_index=True, max_length=60),
                ),
                (
                    "party_name",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("trans_type", models.CharField(blank=True, max_length=120)),
                (
                    "trans_no",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("trans_date_display", models.CharField(blank=True, max_length=40)),
                ("due_date_display", models.CharField(blank=True, max_length=40)),
                ("overdue_date_display", models.CharField(blank=True, max_length=40)),
                ("trans_date", models.DateField(blank=True, db_index=True, null=True)),
                ("due_date", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "overdue_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "bill_amt",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "paid_amt",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "outstanding_amt",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("item_name", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "customer_po_no",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                (
                    "customer_po_date_display",
                    models.CharField(blank=True, max_length=40),
                ),
                (
                    "customer_po_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ACCOUNTS_receivablesnapshotrow",
            },
        ),
        migrations.AddConstraint(
            model_name="outgoingemailaccount",
            constraint=models.UniqueConstraint(
                fields=("company_group", "from_email"),
                name="uq_outgoing_email_account_group_email",
            ),
        ),
        migrations.AddField(
            model_name="partycontact",
            name="party",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="receivable.party",
            ),
        ),
        migrations.AddField(
            model_name="paymenttargetweek",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_targets_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymenttargetline",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="receivable.paymenttargetweek",
            ),
        ),
        migrations.AddField(
            model_name="pdcreminderlog",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="receivable",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receivables_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pdcreminderlog",
            name="receivable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pdc_reminders",
                to="receivable.receivable",
            ),
        ),
        migrations.AddIndex(
            model_name="receivablesnapshotrow",
            index=models.Index(
                fields=["snapshot_date", "party_code"],
                name="ACCOUNTS_re_snapsho_610927_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="receivablesnapshotrow",
            index=models.Index(
                fields=["snapshot_date", "party_name"],
                name="ACCOUNTS_re_snapsho_54449f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="receivablesnapshotrow",
            index=models.Index(
                fields=["snapshot_date", "trans_no"],
                name="ACCOUNTS_re_snapsho_6998da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="receivablesnapshotrow",
            index=models.Index(
                fields=["snapshot_date", "company_name"],
                name="ACCOUNTS_re_snapsho_fcf3b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="receivablesnapshotrow",
            index=models.Index(
                fields=["snapshot_date", "party_code", "trans_no"],
                name="ix_rcv_snap_pc_inv",
            ),
        ),
        migrations.AddIndex(
            model_name="receivablesnapshotrow",
            index=models.Index(
                fields=["snapshot_date", "paid_amt"], name="ix_rcv_snap_paid"
            ),
        ),
        migrations.AddIndex(
            model_name="receivablesnapshotrow",
            index=models.Index(
                fields=["snapshot_date", "outstanding_amt"], name="ix_rcv_snap_os"
            ),
        ),
        migrations.AddIndex(
            model_name="receivablesnapshotrow",
            index=models.Index(
                fields=["snapshot_date", "trans_date"], name="ix_rcv_snap_transdt"
            ),
        ),
        migrations.AddIndex(
            model_name="receivablesnapshotrow",
            index=models.Index(
                fields=["snapshot_date", "due_date"], name="ix_rcv_snap_duedt"
            ),
        ),
        migrations.AddIndex(
            model_name="receivablesnapshotrow",
            index=models.Index(
                fields=["snapshot_date", "overdue_date"], name="ix_rcv_snap_overduedt"
            ),
        ),
        migrations.AddIndex(
            model_name="receivablesnapshotrow",
            index=models.Index(
                fields=["snapshot_date", "customer_po_no"], name="ix_rcv_snap_pono"
            ),
        ),
        migrations.AddIndex(
            model_name="receivablesnapshotrow",
            index=models.Index(
                fields=["snapshot_date", "customer_po_date"], name="ix_rcv_snap_podt"
            ),
        ),
        migrations.AddConstraint(
            model_name="receivablesnapshotrow",
            constraint=models.UniqueConstraint(
                fields=("snapshot_date", "erp_lid", "party_code", "trans_no"),
                name="uq_receivable_snapshotrow",
            ),
        ),
        migrations.AddIndex(
            model_name="partycontact",
            index=models.Index(fields=["email"], name="ACCOUNTS_pa_email_568051_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttargetweek",
            index=models.Index(
                fields=["week_start", "week_end"], name="ACCOUNTS_pa_week_st_3ad8d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttargetweek",
            index=models.Index(
                fields=["company_group", "week_start"],
                name="ACCOUNTS_pa_company_79d0f5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttargetline",
            index=models.Index(
                fields=["target", "party_code"], name="ACCOUNTS_pa_target__ebc5c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttargetline",
            index=models.Index(
                fields=["target", "invoice_no"], name="ACCOUNTS_pa_target__184f5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttargetline",
            index=models.Index(
                fields=["party_code", "invoice_no"],
                name="ACCOUNTS_pa_party_c_11f3f7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttargetline",
            constraint=models.UniqueConstraint(
                fields=("target", "party_code", "invoice_no"),
                name="uq_target_party_invoice",
            ),
        ),
        migrations.AddConstraint(
            model_name="pdcreminderlog",
            constraint=models.UniqueConstraint(
                fields=("receivable", "reminder_date"),
                name="uq_pdc_reminder_receivable_date",
            ),
        ),
    ]
