# Generated by Django 5.0.11 on 2025-12-30 10:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receivable", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receivable",
            name="entry_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
