# Generated by Django 5.0.11 on 2026-01-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receivable", "0002_receivable_entry_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="receivable",
            name="instrument_no",
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="receivablesnapshotrow",
            name="instrument_no",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=120
            ),
        ),
        migrations.AddIndex(
            model_name="receivablesnapshotrow",
            index=models.Index(
                fields=["snapshot_date", "instrument_no"], name="ix_rcv_snap_instno"
            ),
        ),
    ]
