# Generated by Django 5.0.11 on 2026-02-10 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receivable", "0003_receivable_instrument_no_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceivableOutstandingRemark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField(db_index=True)),
                ("party_code", models.CharField(db_index=True, max_length=50)),
                ("invoice_no", models.CharField(db_index=True, max_length=100)),
                (
                    "company_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "party_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal follow-up remark entered by the user for this customer/invoice.",
                        verbose_name="Remark by the user for the customer",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outstanding_remarks_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outstanding_remarks_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["snapshot_date", "party_code"],
                        name="receivable__snapsho_daa90d_idx",
                    ),
                    models.Index(
                        fields=["snapshot_date", "invoice_no"],
                        name="receivable__snapsho_bdf606_idx",
                    ),
                ],
                "unique_together": {("snapshot_date", "party_code", "invoice_no")},
            },
        ),
    ]
