# Generated by Django 5.0.11 on 2025-08-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PRODUCTION", "0003_rename_ideal_downtime_idle"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="downtime",
            options={
                "verbose_name": "Downtime Record",
                "verbose_name_plural": "Downtime Records",
            },
        ),
        migrations.AlterField(
            model_name="downtime",
            name="downtime_category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name="downtime",
            table="production_downtime",
        ),
        migrations.CreateModel(
            name="DeptCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Department Category",
                "verbose_name_plural": "Department Categories",
                "db_table": "production_category_master",
                "ordering": ["department", "category"],
                "unique_together": {("department", "category")},
            },
        ),
    ]
