# Generated by Django 5.0.11 on 2025-12-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PRODUCTION", "0004_alter_downtime_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DowntimeCriticalEquip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eqp", models.CharField(db_column="eqp", max_length=50)),
                ("fg", models.CharField(db_column="fg", max_length=255)),
                ("stage", models.CharField(db_column="stage", max_length=255)),
                ("from_date", models.DateField(db_column="from_date")),
                ("to_date", models.DateField(db_column="to_date")),
            ],
            options={
                "db_table": "downtime_critical_equip",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="downtime",
            name="batch_size",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
