# Generated by Django 5.0.11 on 2025-08-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HR", "0006_alter_overtimereport_pending_with"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortleave",
            name="pending_with",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
