# Generated by Django 5.0.11 on 2025-09-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HR", "0007_alter_shortleave_pending_with"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyattendance",
            name="sub_department",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
