# Generated by Django 5.0.11 on 2025-09-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HR", "0008_dailyattendance_sub_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyattendance",
            name="sub_department",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
