# Generated by Django 5.0.11 on 2025-12-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HR", "0009_alter_dailyattendance_sub_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeJoining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_name",
                    models.CharField(max_length=100, verbose_name="Employee Name"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        choices=[
                            (
                                "OC Specialities Chemicals Pvt. Ltd",
                                "OC Specialities Chemicals Pvt. Ltd",
                            ),
                            ("OC Specialities Pvt.Ltd", "OC Specialities Pvt.Ltd"),
                        ],
                        max_length=150,
                        verbose_name="Company",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Mumbai", "Mumbai"),
                            ("Solapur", "Solapur"),
                            ("Vasai", "Vasai"),
                            ("Virar", "Virar"),
                        ],
                        max_length=100,
                        verbose_name="Location",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Accounts", "Accounts"),
                            ("ADL", "ADL"),
                            ("Admin", "Admin"),
                            ("Boiler", "Boiler"),
                            ("Business Development", "Business Development"),
                            (
                                "Business Development & Strategy (Personal Care)",
                                "Business Development & Strategy (Personal Care)",
                            ),
                            (
                                "Business Development &Strategy (Agrochemicals)",
                                "Business Development &Strategy (Agrochemicals)",
                            ),
                            ("EHS", "EHS"),
                            ("Electrical", "Electrical"),
                            ("Engineering", "Engineering"),
                            ("Environment", "Environment"),
                            ("Finance", "Finance"),
                            ("HR", "HR"),
                            ("Import Export", "Import Export"),
                            ("Instrument", "Instrument"),
                            ("IT", "IT"),
                            ("Logistic", "Logistic"),
                            ("Maintenance", "Maintenance"),
                            ("Management", "Management"),
                            ("Marketing", "Marketing"),
                            ("MD's Office", "MD's Office"),
                            ("Operation", "Operation"),
                            ("PD Lab", "PD Lab"),
                            ("Personal Care", "Personal Care"),
                            ("Production", "Production"),
                            ("Project", "Project"),
                            ("Project & Maintenance", "Project & Maintenance"),
                            ("Purchase", "Purchase"),
                            ("QC & QA", "QC & QA"),
                            ("Quality Assurance", "Quality Assurance"),
                            ("Quality Control", "Quality Control"),
                            ("R & D", "R & D"),
                            ("Sales", "Sales"),
                            ("Sales & Logistics", "Sales & Logistics"),
                            ("SCM", "SCM"),
                            ("Store", "Store"),
                            ("Technical Services", "Technical Services"),
                            ("Utility", "Utility"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_of_joining", models.DateField(verbose_name="Date of Joining")),
                (
                    "date_of_confirmation",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Confirmation"
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Employee ID"
                    ),
                ),
                (
                    "Biomatric_enrollment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Applicable", "Applicable"),
                            ("Not Applicable", "Not Applicable"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="BioMetric Enrollment",
                    ),
                ),
                (
                    "attendance_card",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Applicable", "Applicable"),
                            ("Not Applicable", "Not Applicable"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Attendance Card",
                    ),
                ),
                (
                    "smart_office_entry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Applicable", "Applicable"),
                            ("Not Applicable", "Not Applicable"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Smart Office Entry",
                    ),
                ),
                (
                    "teamnest_hr_app_entry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Applicable", "Applicable"),
                            ("Not Applicable", "Not Applicable"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="TeamNest HR App Entry",
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Applicable", "Applicable"),
                            ("Not Applicable", "Not Applicable"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Mobile Phone",
                    ),
                ),
                (
                    "sim_card",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Existing Card", "Existing Card"),
                            ("New Card", "New Card"),
                            ("Not Applicable", "Not Applicable"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="SIM Card",
                    ),
                ),
                (
                    "telephone_extension",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Applicable", "Applicable"),
                            ("Not Applicable", "Not Applicable"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Telephone Extension",
                    ),
                ),
                (
                    "computer",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Desktop", "Desktop"),
                            ("Laptop", "Laptop"),
                            ("Not Applicable", "Not Applicable"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Computer",
                    ),
                ),
                (
                    "tally_login",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Applicable", "Applicable"),
                            ("Not Applicable", "Not Applicable"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Tally Login",
                    ),
                ),
                (
                    "office_365_id",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Applicable", "Applicable"),
                            ("Not Applicable", "Not Applicable"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Office 365 ID",
                    ),
                ),
                (
                    "email_id",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email ID"
                    ),
                ),
                (
                    "sharepoint_site",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="SharePoint Site",
                    ),
                ),
                (
                    "specific_folder_rights",
                    models.TextField(
                        blank=True, null=True, verbose_name="Specific Folder Rights"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="Remark"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Employee Joining",
                "verbose_name_plural": "Employee Joining Records",
                "db_table": "employee_joining",
            },
        ),
    ]
