# Generated by Django 5.0.11 on 2025-12-11 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HR", "0010_employeejoining"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employeejoining",
            name="approval_remark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeejoining",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeejoining",
            name="hr_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeejoining",
            name="hr_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="joining_hr_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Joining HR User",
            ),
        ),
        migrations.AddField(
            model_name="employeejoining",
            name="it_approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="joining_approved",
                to=settings.AUTH_USER_MODEL,
                verbose_name="IT Approver",
            ),
        ),
        migrations.AddField(
            model_name="employeejoining",
            name="it_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeejoining",
            name="it_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="joining_it_processed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="IT Infra User",
            ),
        ),
        migrations.AddField(
            model_name="employeejoining",
            name="status",
            field=models.CharField(
                choices=[
                    ("hr_submitted", "HR Submitted (Pending IT)"),
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="hr_submitted",
                max_length=30,
                verbose_name="Status",
            ),
        ),
    ]
