# Generated by Django 5.0.11 on 2025-12-11 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("HR", "0011_employeejoining_approval_remark_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeejoining",
            name="teamnest_hr_app_entry",
        ),
    ]
