# Generated by Django 5.0.11 on 2026-01-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HR", "0012_remove_employeejoining_teamnest_hr_app_entry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeejoining",
            name="tally_login",
        ),
        migrations.AddField(
            model_name="employeejoining",
            name="erp_login",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Applicable", "Applicable"),
                    ("Not Applicable", "Not Applicable"),
                ],
                max_length=20,
                null=True,
                verbose_name="ERP Login",
            ),
        ),
    ]
