# Generated by Django 5.0.11 on 2025-07-17 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CANTEEN", "0004_alter_employee_employee_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="employee_ref",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Original Employee ID at time of punch",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendances",
                to="CANTEEN.employee",
            ),
        ),
    ]
