# Generated by Django 5.0.11 on 2025-07-18 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CANTEEN", "0005_attendance_employee_ref_alter_attendance_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendances",
                to="CANTEEN.employee",
            ),
        ),
    ]
