# Generated by Django 5.0.11 on 2025-07-18 05:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CANTEEN", "0006_alter_attendance_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="employee_ref",
        ),
    ]
