# Generated by Django 5.0.11 on 2026-01-21 12:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CANTEEN", "0007_remove_attendance_employee_ref"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanteenHeadCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("punched_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "meal_type",
                    models.CharField(
                        blank=True,
                        choices=[("Lunch", "Lunch"), ("Dinner", "Dinner")],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="CanteenHeadCount",
                        to="CANTEEN.employee",
                    ),
                ),
            ],
            options={
                "db_table": "canteen_headcount",
            },
        ),
    ]
