# Generated by Django 5.0.11 on 2026-01-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InvoicePostShipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(max_length=50, verbose_name="Invoice No."),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Transaction Type",
                    ),
                ),
                ("invoice_date", models.DateField(verbose_name="Invoice Date")),
                (
                    "buyers_order_no",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Buyer's Order No.",
                    ),
                ),
                (
                    "buyers_order_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Buyer's Order Date"
                    ),
                ),
                (
                    "consignee_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Consignee Name",
                    ),
                ),
                (
                    "consignee_address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Consignee Address"
                    ),
                ),
                (
                    "notify_party1_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Notify Party 1 Name",
                    ),
                ),
                (
                    "notify_party1_address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notify Party 1 Address"
                    ),
                ),
                (
                    "notify_party2_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Notify Party 2 Name",
                    ),
                ),
                (
                    "notify_party2_address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notify Party 2 Address"
                    ),
                ),
                (
                    "country_origin",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Country of Origin of Goods",
                    ),
                ),
                (
                    "country_destination",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Country of Final Destination",
                    ),
                ),
                (
                    "district_origin",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="District of Origin of Goods",
                    ),
                ),
                (
                    "state_origin",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="State of Origin of Goods",
                    ),
                ),
                (
                    "vessel_name_no",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Vessel Name & No.",
                    ),
                ),
                (
                    "port_loading",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Port of Loading",
                    ),
                ),
                (
                    "port_discharge",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Port of Discharge",
                    ),
                ),
                (
                    "final_destination",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Final Destination",
                    ),
                ),
                (
                    "preferential_agreement",
                    models.CharField(
                        blank=True,
                        default="NO",
                        max_length=10,
                        null=True,
                        verbose_name="Preferential Agreement",
                    ),
                ),
                (
                    "standard_unit_qty_code",
                    models.CharField(
                        blank=True,
                        default="KGS",
                        max_length=20,
                        null=True,
                        verbose_name="Standard Unit Quantity Code",
                    ),
                ),
                ("delivery", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "shipment_mode",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "payment_terms",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "due_date",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Payment Due Date (text)",
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "bank_account_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("ad_code", models.CharField(blank=True, max_length=50, null=True)),
                ("swift_code", models.CharField(blank=True, max_length=50, null=True)),
                ("bank_address", models.TextField(blank=True, null=True)),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "container_no",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Container No.",
                    ),
                ),
                (
                    "merks_and_container_no",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Merks/No & Container No.",
                    ),
                ),
                (
                    "merks_and_container_no1",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="Merks/No & Container No.1",
                    ),
                ),
                (
                    "packing_details",
                    models.TextField(
                        blank=True, null=True, verbose_name="No. & Kind of Packing"
                    ),
                ),
                (
                    "description_of_goods",
                    models.CharField(
                        blank=True,
                        max_length=70,
                        null=True,
                        verbose_name="Description of Goods",
                    ),
                ),
                (
                    "item_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Item No."
                    ),
                ),
                (
                    "hsn_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="HSN No."
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Quantity"
                    ),
                ),
                (
                    "quantity_unit",
                    models.CharField(
                        default="KILOGRAMS", max_length=50, verbose_name="Quantity Unit"
                    ),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="Conversion Rate",
                    ),
                ),
                (
                    "rate_usd",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="Rate (US$)"
                    ),
                ),
                (
                    "amount_usd",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Amount (US$)"
                    ),
                ),
                (
                    "gross_wt",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Gross wt"
                    ),
                ),
                (
                    "bl_number",
                    models.CharField(
                        max_length=50, verbose_name="Bill of Lading Number"
                    ),
                ),
                ("bl_date", models.DateField(verbose_name="Bill of Lading Date")),
                (
                    "shipping_bill_no",
                    models.CharField(
                        max_length=50, verbose_name="Shipping Bill Number"
                    ),
                ),
                (
                    "shipping_bill_date",
                    models.DateField(verbose_name="Shipping Bill Date"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "invoice_post_shipment",
                "ordering": ["-invoice_date", "invoice_number"],
            },
        ),
    ]
