# Generated by Django 5.0.11 on 2026-01-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Export_Commercial_Invoice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicepostshipment",
            name="attachment",
            field=models.BinaryField(
                blank=True, max_length="max", null=True, verbose_name="Attachment"
            ),
        ),
        migrations.AddField(
            model_name="invoicepostshipment",
            name="attachment_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Attachment file name",
            ),
        ),
    ]
