# Generated by Django 5.0.11 on 2025-08-26 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CREDENTIALS", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtentionList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Directors", "Directors"),
                            (
                                "Board/Reception( Office 205)",
                                "Board/Reception( Office 205)",
                            ),
                            ("Reception(Office 206)", "Reception(Office 206)"),
                            ("Executive Asst.", "Executive Asst."),
                            ("Business Development", "Business Development"),
                            ("Operation", "Operation"),
                            ("Personal Care", "Personal Care"),
                            ("Sales", "Sales"),
                            ("Purchase", "Purchase"),
                            ("Dispatch", "Dispatch"),
                            ("Finance & Account", "Finance & Account"),
                            ("Import & Export", "Import & Export"),
                            ("Logistics", "Logistics"),
                            ("HR & Admin", "HR & Admin"),
                            ("IT", "IT"),
                            ("Office Boy", "Office Boy"),
                            ("QA & QC", "QA & QC"),
                            ("Engineering", "Engineering"),
                            ("Production", "Production"),
                            ("Production Block", "Production Block"),
                            ("EHS", "EHS"),
                            ("Intstrumentation", "Intstrumentation"),
                            ("Store", "Store"),
                            ("Project", "Project"),
                            ("Utility", "Utility"),
                            ("E-17 Reception", "E-17 Reception"),
                            ("Security", "Security"),
                            ("Others", "Others"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "extension_no",
                    models.CharField(
                        blank=True,
                        help_text="Enter one or two extensions, separated by comma (e.g., 205,206)",
                        max_length=20,
                        null=True,
                        verbose_name="Extension No.",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        help_text="10–15 digits, optional +",
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?\\d{10,15}$", "Enter a valid phone number"
                            )
                        ],
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Solapur", "Solapur"),
                            ("Mumbai", "Mumbai"),
                            ("Virar", "Virar"),
                            ("Vasai", "Vasai"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Extension List",
                "verbose_name_plural": "Extension List",
                "db_table": "extension_list",
                "ordering": ["name"],
            },
        ),
    ]
