# Generated by Django 5.0.11 on 2025-08-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CREDENTIALS", "0002_extentionlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="extentionlist",
            name="designation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Director", "Director"),
                    ("Sr.Vice President", "Sr.Vice President"),
                    ("Vice President", "Vice President"),
                    ("Asst. General Manager", "Asst. General Manager"),
                    ("Sr. Manager", "Sr. Manager"),
                    ("Manager", "Manager"),
                    ("Asst. Manager", "Asst. Manager"),
                    (
                        "Sr. Manager Finance & Accounts",
                        "Sr. Manager Finance & Accounts",
                    ),
                    ("Officer", "Officer"),
                    ("Officer", "Officer"),
                    ("None", "None"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
