# Generated by Django 5.0.11 on 2026-01-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CapexGrnLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_no",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="BatchNo"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Location"
                    ),
                ),
                (
                    "virtual_location",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Virtual Location",
                    ),
                ),
                ("item_code", models.CharField(db_index=True, max_length=50)),
                ("item_name", models.CharField(max_length=255)),
                (
                    "doc_no",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="DocNo"
                    ),
                ),
                (
                    "txn_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="TxnTotal"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=18, verbose_name="Quantity"
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, verbose_name="Rate"
                    ),
                ),
                (
                    "rate_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="Rate Amount"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="Total Amount"
                    ),
                ),
            ],
            options={
                "db_table": "capex_grn_line",
                "indexes": [
                    models.Index(
                        fields=["doc_no"], name="capex_grn_l_doc_no_80bb76_idx"
                    ),
                    models.Index(
                        fields=["item_code"], name="capex_grn_l_item_co_3b35d5_idx"
                    ),
                    models.Index(
                        fields=["batch_no"], name="capex_grn_l_batch_n_08c585_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MaterialIssueLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_date",
                    models.DateField(
                        blank=True,
                        help_text="Document date",
                        null=True,
                        verbose_name="DocDate",
                    ),
                ),
                (
                    "material_requisition_date",
                    models.DateField(
                        blank=True,
                        help_text="Material requisition date from header CF",
                        null=True,
                        verbose_name="Material Requisition Date",
                    ),
                ),
                (
                    "batch_no",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="BatchNo"
                    ),
                ),
                (
                    "location_from",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Location From",
                    ),
                ),
                (
                    "virtual_location",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Virtual Location",
                    ),
                ),
                ("item_code", models.CharField(db_index=True, max_length=50)),
                ("item_name", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, max_digits=18, verbose_name="Quantity"
                    ),
                ),
                (
                    "txn_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Header-level total (d.dTotal)",
                        max_digits=18,
                        verbose_name="TxnTotal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material Issue Line",
                "verbose_name_plural": "Material Issue Lines",
                "db_table": "material_issue_line",
                "indexes": [
                    models.Index(
                        fields=["doc_date"], name="material_is_doc_dat_9a8854_idx"
                    ),
                    models.Index(
                        fields=["item_code"], name="material_is_item_co_57db7b_idx"
                    ),
                    models.Index(
                        fields=["batch_no"], name="material_is_batch_n_5d83f7_idx"
                    ),
                    models.Index(
                        fields=["location_from"], name="material_is_locatio_917b80_idx"
                    ),
                ],
            },
        ),
    ]
