# Generated by Django 5.0.11 on 2026-02-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material_issue_capex", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialissueline",
            name="doc_no",
            field=models.CharField(
                blank=True,
                help_text="Document Number",
                max_length=100,
                null=True,
                verbose_name="DocNumber",
            ),
        ),
    ]
