# Generated by Django 5.0.11 on 2026-03-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material_issue_capex", "0002_materialissueline_doc_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationStockTransferCapex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location_transfer_capex_no", models.CharField(max_length=100)),
                ("location_transfer_capex_date", models.DateField()),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "to_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("item_code", models.CharField(max_length=100)),
                ("item_name", models.CharField(max_length=255)),
                ("batch_no", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "transfer_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=18),
                ),
                (
                    "issue_value",
                    models.DecimalField(decimal_places=3, default=0, max_digits=18),
                ),
                (
                    "virtual_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "location_stock_transfer_capex",
                "indexes": [
                    models.Index(
                        fields=["location_transfer_capex_no"],
                        name="location_st_locatio_44bf6f_idx",
                    ),
                    models.Index(
                        fields=["location_transfer_capex_date"],
                        name="location_st_locatio_5b6e45_idx",
                    ),
                    models.Index(
                        fields=["item_code"], name="location_st_item_co_27ac75_idx"
                    ),
                    models.Index(
                        fields=["batch_no"], name="location_st_batch_n_bb7b81_idx"
                    ),
                ],
            },
        ),
    ]
