# Generated by Django 5.0.11 on 2025-08-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CogsReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "to_emails",
                    models.TextField(
                        help_text="Comma separated emails, e.g. a@b.com, c@d.com"
                    ),
                ),
                ("subject", models.CharField(default="COGS Report", max_length=200)),
                ("greet", models.CharField(default="Team", max_length=80)),
                ("company_id", models.IntegerField(default=27)),
                ("year_id", models.IntegerField(default=7)),
                ("cust_code", models.IntegerField(default=0)),
                ("item_id", models.IntegerField(default=0)),
                ("txn_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "customer_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("item_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "date_range",
                    models.CharField(
                        choices=[
                            ("yesterday", "Yesterday"),
                            ("last7", "Last 7 days"),
                            ("mtd", "Month-to-date"),
                            ("custom", "Custom (use from/to)"),
                        ],
                        default="mtd",
                        max_length=20,
                    ),
                ),
                ("from_date", models.DateField(blank=True, null=True)),
                ("to_date", models.DateField(blank=True, null=True)),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("CRON", "CRON (advanced)"),
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                        ],
                        default="DAILY",
                        max_length=10,
                    ),
                ),
                ("hour", models.CharField(default="10", max_length=20)),
                ("minute", models.CharField(default="30", max_length=20)),
                (
                    "day_of_week",
                    models.CharField(
                        default="mon-fri",
                        help_text="Only for WEEKLY (e.g., 'mon-fri' or 'sun'). Ignored for DAILY.",
                        max_length=20,
                    ),
                ),
                (
                    "cron_month",
                    models.CharField(default="*", help_text="1-12 or *", max_length=20),
                ),
                (
                    "cron_day",
                    models.CharField(default="*", help_text="1-31 or *", max_length=20),
                ),
                (
                    "cron_dow",
                    models.CharField(
                        default="*", help_text="mon-sun or *", max_length=20
                    ),
                ),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=64)),
                (
                    "last_run_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
