# Generated by Django 5.0.11 on 2025-08-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductionSchedule",
            fields=[
                ("schedule_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_id", models.CharField(blank=True, max_length=150, null=True)),
                ("stage_name", models.CharField(blank=True, max_length=150, null=True)),
                ("type", models.CharField(blank=True, max_length=80, null=True)),
                ("start_date", models.DateTimeField()),
                ("closed_date", models.DateField(blank=True, null=True)),
                ("no_of_batches", models.IntegerField(default=0)),
                ("scheduling_approach", models.IntegerField(default=0)),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "db_table": "production_schedule",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductionScheduleLine",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("line_type", models.CharField(max_length=20)),
                (
                    "material_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "material_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=18, null=True
                    ),
                ),
                (
                    "ratio",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=18, null=True
                    ),
                ),
                (
                    "density",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=18, null=True
                    ),
                ),
                (
                    "litre",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=18, null=True
                    ),
                ),
                ("include_in_total", models.BooleanField(default=True)),
                (
                    "equipment_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "std_bct",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=18, null=True
                    ),
                ),
                (
                    "wait_time",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=18, null=True
                    ),
                ),
                ("star", models.BooleanField(default=False)),
                ("closed_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "production_schedule_line",
                "managed": False,
            },
        ),
    ]
