# Generated by Django 5.0.11 on 2025-11-25 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MEEReadingCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Unit of measurement, e.g. KL, MT, °C",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order in Utility Entry tabs (lower = left side)",
                    ),
                ),
            ],
            options={
                "db_table": "mee_reading_category",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MEEReadingSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order in tabs/header (lower = left).",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="MEE.meereadingcategory",
                    ),
                ),
            ],
            options={
                "db_table": "mee_reading_Subcategory",
                "ordering": ["category", "order", "id"],
                "unique_together": {("category", "name")},
            },
        ),
        migrations.CreateModel(
            name="MEEDailyReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reading_date", models.DateField()),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mee_daily_readings",
                        to="MEE.meereadingsubcategory",
                    ),
                ),
            ],
            options={
                "db_table": "mee_daily_reading",
                "ordering": ["reading_date", "subcategory"],
                "unique_together": {("reading_date", "subcategory")},
            },
        ),
    ]
