# Generated by Django 5.0.11 on 2025-11-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MEE", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meedailyreading",
            name="downtime_end",
            field=models.DateTimeField(
                blank=True, help_text="Downtime end (date & time)", null=True
            ),
        ),
        migrations.AddField(
            model_name="meedailyreading",
            name="downtime_start",
            field=models.DateTimeField(
                blank=True, help_text="Downtime start (date & time)", null=True
            ),
        ),
        migrations.AddField(
            model_name="meedailyreading",
            name="reason",
            field=models.CharField(
                blank=True, help_text="Downtime reason", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="meedailyreading",
            name="total_downtime",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total downtime in hours (auto calculated)",
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="meedailyreading",
            name="value",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
    ]
