# Generated by Django 5.0.11 on 2025-11-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MEE", "0002_meedailyreading_downtime_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meedailyreading",
            name="downtime_end",
            field=models.TimeField(
                blank=True, help_text="Downtime end (time only, e.g. 10:45)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="meedailyreading",
            name="downtime_start",
            field=models.TimeField(
                blank=True,
                help_text="Downtime start (time only, e.g. 09:15)",
                null=True,
            ),
        ),
    ]
