# Generated by Django 5.0.11 on 2025-12-02 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MEE", "0003_alter_meedailyreading_downtime_end_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meedailyreading",
            name="downtime_end",
        ),
        migrations.RemoveField(
            model_name="meedailyreading",
            name="downtime_start",
        ),
        migrations.RemoveField(
            model_name="meedailyreading",
            name="reason",
        ),
        migrations.RemoveField(
            model_name="meedailyreading",
            name="total_downtime",
        ),
        migrations.CreateModel(
            name="MEEDowntime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("downtime_start", models.DateTimeField(blank=True, null=True)),
                ("downtime_end", models.DateTimeField(blank=True, null=True)),
                (
                    "downtime_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Duration in hours",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Downtime reason",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "reading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downtimes",
                        to="MEE.meedailyreading",
                    ),
                ),
            ],
            options={
                "db_table": "mee_downtime",
                "ordering": ["reading__reading_date", "downtime_start"],
            },
        ),
    ]
