# Generated by Django 5.0.11 on 2025-12-19 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MEE", "0004_remove_meedailyreading_downtime_end_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ATFDDowntime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("downtime_start", models.DateTimeField(blank=True, null=True)),
                ("downtime_end", models.DateTimeField(blank=True, null=True)),
                (
                    "downtime_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Duration in hours",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Downtime reason",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "atfd_downtime",
                "ordering": ["reading__reading_date", "downtime_start"],
            },
        ),
        migrations.CreateModel(
            name="ATFDReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reading_date", models.DateField(db_index=True)),
                (
                    "effluent_feed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="ATFD Feed (KL)",
                    ),
                ),
                (
                    "steam_consume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="Steam Consume (MT)",
                    ),
                ),
                (
                    "steam_economy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Auto: ATFD Feed / Steam Consume",
                        max_digits=12,
                        null=True,
                        verbose_name="Steam Economy (KL/MT)",
                    ),
                ),
                (
                    "blower_draft",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="Blower Draft(mmWC)",
                    ),
                ),
                (
                    "steam_inlet_pressure",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="Stean Inlet Pressure(kg/cm2)",
                    ),
                ),
                (
                    "atfd_rpm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="ATFD RPM",
                    ),
                ),
                (
                    "atfd_salt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        verbose_name="ATFD Salt (MT)",
                    ),
                ),
                (
                    "effluent_feed_ph",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Effluent Feed pH",
                    ),
                ),
                (
                    "effluent_feed_TDS",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Effluent Feed TDS(%)",
                    ),
                ),
                (
                    "effluent_feed_cod",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Effluent Feed cod(%)",
                    ),
                ),
                (
                    "effluent_feed_spgr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="Effluent Feed spGr",
                    ),
                ),
                (
                    "atfd_qty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="ATFD Vapor condensate Qty(KL)",
                    ),
                ),
                (
                    "vapor_contensate_ph",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="ATFD Vapor condensate pH",
                    ),
                ),
                (
                    "vapor_contensate_tds",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="ATFD Vapor condensate TDS(%)",
                    ),
                ),
                (
                    "vapor_contensate_cod",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="ATFD Vapor condensate COD(%)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "atfd_reading",
                "ordering": ["-reading_date"],
            },
        ),
        migrations.AddConstraint(
            model_name="atfdreading",
            constraint=models.UniqueConstraint(
                fields=("reading_date",), name="uq_atfd_reading_date"
            ),
        ),
        migrations.AddField(
            model_name="atfddowntime",
            name="reading",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="downtimes",
                to="MEE.atfdreading",
            ),
        ),
    ]
