# Generated by Django 5.0.11 on 2025-07-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QC", "0002_alter_spec_options_alter_spec_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SampleDescriptionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Sample Description Option",
                "verbose_name_plural": "Sample Description Options",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="qcentry",
            name="ar_type",
            field=models.CharField(
                choices=[
                    ("RM", "Raw Material"),
                    ("PM", "Packing Material"),
                    ("IP", "In-Process"),
                    ("FG", "Finished Goods"),
                ],
                default="RM",
                help_text="Category for AR number generation",
                max_length=2,
                verbose_name="AR Category",
            ),
        ),
        migrations.AddField(
            model_name="qcentry",
            name="sample_description_text",
            field=models.TextField(
                blank=True,
                help_text="Additional notes about the sample (up to 250 chars).",
                max_length=250,
                verbose_name="Description Notes",
            ),
        ),
        migrations.AddField(
            model_name="spec",
            name="acceptance_criteria",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Deviation limit outside Min/Max range (e.g. < Min or > Max).",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="spec",
            name="unit",
            field=models.CharField(
                blank=True, help_text="Display unit, e.g. °C, %, ppm", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="qcentry",
            name="decision_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("approved", "Approved"),
                    ("approved_under_deviation", "Approved under deviation"),
                    ("rejected", "Rejected"),
                    ("fail", "Fail"),
                ],
                help_text="QC decision: approved, approved under deviation, or rejected",
                max_length=30,
                null=True,
            ),
        ),
    ]
