# Generated by Django 5.0.11 on 2025-07-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QC", "0003_sampledescriptionoption_qcentry_ar_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spec",
            name="acceptance_criteria",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Deviation limit outside Min/Max range (e.g. < Min or > Max).",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spec",
            name="max_val",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="spec",
            name="min_val",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=8, null=True
            ),
        ),
    ]
