# Generated by Django 5.0.11 on 2025-07-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QC", "0004_alter_spec_acceptance_criteria_alter_spec_max_val_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qcentry",
            name="frequency",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
