# Generated by Django 5.0.11 on 2025-07-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QC", "0006_coarecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="QCTestParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "QC Test Parameter",
                "verbose_name_plural": "QC Test Parameters",
                "db_table": "qc_test_parameter",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelTable(
            name="sampledescriptionoption",
            table="sample_description",
        ),
    ]
