# Generated by Django 5.0.11 on 2025-07-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QC", "0007_qctestparameter_alter_sampledescriptionoption_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="qcentry",
            name="instrument_id",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OCSPL/QC/GC/001", "OCSPL/QC/GC/001"),
                    ("OCSPL/QC/GC/003", "OCSPL/QC/GC/003"),
                    ("OCSPL/QC/GC/004", "OCSPL/QC/GC/004"),
                    ("OCSPL/QC/GC/006", "OCSPL/QC/GC/006"),
                    ("OCSPL/QC/GC/007", "OCSPL/QC/GC/007"),
                    ("OCSPL/QC/GC/008", "OCSPL/QC/GC/008"),
                    ("OCSPL/QC/GC/009", "OCSPL/QC/GC/009"),
                    ("OCSPL/QC/GC/010", "OCSPL/QC/GC/010"),
                    ("OCSPL/QC/HPLC/001", "OCSPL/QC/HPLC/001"),
                    ("OCSPL/QC/HPLC/002", "OCSPL/QC/HPLC/002"),
                    ("OCSPL/QC/HPLC/003", "OCSPL/QC/HPLC/003"),
                    ("OCSPL/QC/HPLC/004", "OCSPL/QC/HPLC/004"),
                ],
                help_text="Instrument identifier (e.g. OCSPL/QC/GC/001)",
                max_length=50,
                verbose_name="Instrument ID",
            ),
        ),
        migrations.AddField(
            model_name="qcentry",
            name="test_parameters",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of selected parameters.",
                max_length=500,
                verbose_name="Test Parameters",
            ),
        ),
    ]
