# Generated by Django 5.0.11 on 2025-08-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QC", "0008_qcentry_instrument_id_qcentry_test_parameters"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="localbomdetail",
            options={
                "ordering": ["sr_no"],
                "verbose_name": "Local BOM Detail",
                "verbose_name_plural": "Local BOM Details",
            },
        ),

        # ── Add columns only if missing in DB, but always update Django state ──
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="qcentry",
                    name="fg_qty",
                    field=models.DecimalField(
                        blank=True,
                        null=True,
                        max_digits=12,
                        decimal_places=3,
                        help_text="Finished Goods quantity (only used on FGQC form).",
                    ),
                ),
                migrations.AddField(
                    model_name="spec",
                    name="is_critical",
                    field=models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Tick if this specification is critical (master definition).",
                    ),
                ),
                migrations.AddField(
                    model_name="specentry",
                    name="is_critical",
                    field=models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Critical at the time of entry (copied from master Spec).",
                    ),
                ),
            ],
            database_operations=[
                # qc_entry.fg_qty (DECIMAL NULL)
                migrations.RunSQL(
                    sql="""
                        IF COL_LENGTH('qc_entry', 'fg_qty') IS NULL
                        BEGIN
                            ALTER TABLE [qc_entry] ADD [fg_qty] DECIMAL(12,3) NULL;
                        END
                    """,
                    reverse_sql="""
                        IF COL_LENGTH('qc_entry', 'fg_qty') IS NOT NULL
                        BEGIN
                            ALTER TABLE [qc_entry] DROP COLUMN [fg_qty];
                        END
                    """,
                ),
                # qc_spec.is_critical (BIT NOT NULL DEFAULT 0, indexed later by Django)
                migrations.RunSQL(
                    sql="""
                        IF COL_LENGTH('qc_spec', 'is_critical') IS NULL
                        BEGIN
                            ALTER TABLE [qc_spec]
                              ADD [is_critical] BIT NOT NULL CONSTRAINT [DF_qc_spec_is_critical] DEFAULT 0;
                        END
                    """,
                    reverse_sql="""
                        IF COL_LENGTH('qc_spec', 'is_critical') IS NOT NULL
                        BEGIN
                            ALTER TABLE [qc_spec] DROP COLUMN [is_critical];
                        END
                    """,
                ),
                # qc_spec_entry.is_critical (BIT NOT NULL DEFAULT 0)
                migrations.RunSQL(
                    sql="""
                        IF COL_LENGTH('qc_spec_entry', 'is_critical') IS NULL
                        BEGIN
                            ALTER TABLE [qc_spec_entry]
                              ADD [is_critical] BIT NOT NULL CONSTRAINT [DF_qc_spec_entry_is_critical] DEFAULT 0;
                        END
                    """,
                    reverse_sql="""
                        IF COL_LENGTH('qc_spec_entry', 'is_critical') IS NOT NULL
                        BEGIN
                            ALTER TABLE [qc_spec_entry] DROP COLUMN [is_critical];
                        END
                    """,
                ),
            ],
        ),

        # Remaining changes from your original migration
        migrations.AlterField(
            model_name="qcentry",
            name="ar_no",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Analysis Request number assigned by Production.",
                max_length=100,
                verbose_name="AR No.",
            ),
        ),
        migrations.AlterField(
            model_name="qcentry",
            name="instrument_id",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OCSPL/QC/GC/001", "OCSPL/QC/GC/001"),
                    ("OCSPL/QC/GC/003", "OCSPL/QC/GC/003"),
                    ("OCSPL/QC/GC/004", "OCSPL/QC/GC/004"),
                    ("OCSPL/QC/GC/006", "OCSPL/QC/GC/006"),
                    ("OCSPL/QC/GC/007", "OCSPL/QC/GC/007"),
                    ("OCSPL/QC/GC/008", "OCSPL/QC/GC/008"),
                    ("OCSPL/QC/GC/009", "OCSPL/QC/GC/009"),
                    ("OCSPL/QC/GC/010", "OCSPL/QC/GC/010"),
                    ("OCSPL/QC/GC/011", "OCSPL/QC/GC/011"),
                    ("OCSPL/QC/HPLC/001", "OCSPL/QC/HPLC/001"),
                    ("OCSPL/QC/HPLC/002", "OCSPL/QC/HPLC/002"),
                    ("OCSPL/QC/HPLC/003", "OCSPL/QC/HPLC/003"),
                    ("OCSPL/QC/HPLC/004", "OCSPL/QC/HPLC/004"),
                    ("OCSPL/QC/AT/002", "OCSPL/QC/AT/002"),
                    ("OCSPL/QC/KF/003", "OCSPL/QC/KF/003"),
                    ("OCSPL/QC/KF/004", "OCSPL/QC/KF/004"),
                    ("OCSPL/QC/pH/003", "OCSPL/QC/pH/003"),
                    ("OCSPL/QC/pH/004", "OCSPL/QC/pH/004"),
                    ("OCSPL/QC/MR/002", "OCSPL/QC/MR/002"),
                    ("OCSPL/QC/POL/001", "OCSPL/QC/POL/001"),
                    ("OCSPL/QC/UV/001", "OCSPL/QC/UV/001"),
                    ("OCSPL/QC/GT/001", "OCSPL/QC/GT/001"),
                    ("OCSPL/QC/MA/001", "OCSPL/QC/MA/001"),
                    ("OCSPL/QC/MA/002", "OCSPL/QC/MA/002"),
                    ("OCSPL/QC/AM/001", "OCSPL/QC/AM/001"),
                    ("OCSPL/QC/CM/001", "OCSPL/QC/CM/001"),
                    ("None", "None"),
                ],
                help_text="Instrument identifier (e.g. OCSPL/QC/GC/001)",
                max_length=50,
                verbose_name="Instrument ID",
            ),
        ),
        migrations.AlterModelTable(
            name="localbomdetail",
            table="qc_localbomdetail",
        ),
    ]
