# Generated by Django 5.0.11 on 2025-10-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QC", "0009_alter_localbomdetail_options_qcentry_fg_qty_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="localbomdetail",
            options={},
        ),
        migrations.RenameField(
            model_name="qcentry",
            old_name="fg_qty",
            new_name="qty",
        ),
        migrations.AlterField(
            model_name="qcentry",
            name="ar_no",
            field=models.CharField(
                blank=True,
                help_text="Analysis Request number assigned by Production.",
                max_length=100,
                verbose_name="AR No.",
            ),
        ),
        migrations.AlterField(
            model_name="qcentry",
            name="ar_type",
            field=models.CharField(
                choices=[
                    ("RM", "Raw Material"),
                    ("PM", "Packing Material"),
                    ("IP", "In-Process"),
                    ("FG", "Finished Goods"),
                    ("SFG", "Semi Finished Goods"),
                ],
                default="RM",
                help_text="Category for AR number generation",
                max_length=5,
                verbose_name="AR Category",
            ),
        ),
        migrations.AlterModelTable(
            name="localbomdetail",
            table=None,
        ),
    ]
