# Generated by Django 5.0.11 on 2025-10-14 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QC", "0010_alter_localbomdetail_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerComplaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("complaint_date", models.DateField(db_index=True)),
                ("complaint_no", models.CharField(max_length=50, unique=True)),
                ("product_name", models.CharField(max_length=200)),
                ("customer_name", models.CharField(max_length=200)),
                ("nature_of_complaint", models.TextField()),
                ("complaint_type", models.CharField(max_length=150)),
                (
                    "investigation",
                    models.TextField(
                        blank=True, verbose_name="Investigation / Root Cause Analysis"
                    ),
                ),
                ("corrective_action", models.TextField(blank=True)),
                ("preventive_action", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("Under Investigation", "Under Investigation"),
                            ("Closed", "Closed"),
                        ],
                        default="Open",
                        max_length=40,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "qc_customer_complaint",
                "ordering": ["-complaint_date"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticalDowntime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_no",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated, e.g. INC/25-26/00001",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "instrument_id",
                    models.CharField(help_text="HPL-01 / GC-03 / etc.", max_length=50),
                ),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ongoing",
                    models.BooleanField(
                        default=False, help_text="Tick if still ongoing"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("maintenance", "Maintenance"),
                            ("calibration", "Calibration"),
                            ("repair", "Repair"),
                            ("other", "Other"),
                            ("busy", "Busy"),
                        ],
                        default="maintenance",
                        max_length=20,
                    ),
                ),
                ("short_reason", models.CharField(blank=True, max_length=200)),
                ("detail_reason", models.TextField(blank=True)),
                ("stage", models.CharField(blank=True, max_length=120)),
                ("product_name", models.CharField(blank=True, max_length=200)),
                ("batch_no", models.CharField(blank=True, max_length=60)),
                ("tests_delayed", models.PositiveIntegerField(default=0)),
                ("retest_due_date", models.DateField(blank=True, null=True)),
                ("resolved_by", models.CharField(blank=True, max_length=120)),
                ("remarks", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("progress", "In Progress"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "qc_analytical_downtime",
                "ordering": ["-start_at"],
                "indexes": [
                    models.Index(
                        fields=["instrument_id", "status"],
                        name="qc_analytic_instrum_bac59f_idx",
                    ),
                    models.Index(fields=["stage"], name="qc_analytic_stage_8db514_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyQAReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(db_index=True)),
                ("customer_complaints", models.PositiveIntegerField(default=0)),
                ("analytical_mistakes", models.PositiveIntegerField(default=0)),
                ("process_deviations", models.PositiveIntegerField(default=0)),
                ("incident_first_aid_injury", models.PositiveIntegerField(default=0)),
                (
                    "ftr_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "analytical_downtime_hrs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("finished_goods_inspections", models.PositiveIntegerField(default=0)),
                ("any_other_abnormality", models.TextField(blank=True)),
                ("safety_observation_text", models.TextField(blank=True)),
                ("obs_total", models.PositiveIntegerField(default=0)),
                ("obs_closed", models.PositiveIntegerField(default=0)),
                ("obs_open", models.PositiveIntegerField(default=0)),
                ("near_miss_total", models.PositiveIntegerField(default=0)),
                ("near_miss_closed", models.PositiveIntegerField(default=0)),
                ("near_miss_open", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "qc_daily_qareport",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="IncomingGRNCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grn_no", models.CharField(max_length=50)),
                ("grn_date", models.DateField(db_index=True)),
                ("supplier_code", models.CharField(blank=True, max_length=50)),
                ("supplier_name", models.CharField(blank=True, max_length=200)),
                ("item_type", models.CharField(max_length=100)),
                ("item_code", models.CharField(blank=True, max_length=50)),
                ("item_name", models.CharField(max_length=200)),
                ("qty", models.DecimalField(decimal_places=3, max_digits=18)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "qc_incoming_grn_cache",
                "indexes": [
                    models.Index(
                        fields=["grn_date", "item_type"],
                        name="qc_incoming_grn_dat_d3ec13_idx",
                    ),
                    models.Index(
                        fields=["item_code"], name="qc_incoming_item_co_fb06b8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IncomingMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grn_no", models.CharField(blank=True, max_length=50, null=True)),
                ("grn_date", models.DateField(blank=True, db_index=True, null=True)),
                ("supplier_code", models.CharField(blank=True, max_length=50)),
                ("supplier", models.CharField(blank=True, max_length=200)),
                (
                    "material_type",
                    models.CharField(
                        choices=[("RM", "Raw Material"), ("PM", "Packing Material")],
                        default="RM",
                        max_length=2,
                    ),
                ),
                ("material_code", models.CharField(blank=True, max_length=50)),
                ("material", models.CharField(max_length=200)),
                (
                    "qty_mt",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pass", "Pass"),
                            ("Fail", "Fail"),
                            ("Hold", "Hold"),
                            ("NA", "N/A"),
                        ],
                        default="Pass",
                        max_length=10,
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming",
                        to="QC.dailyqareport",
                    ),
                ),
            ],
            options={
                "db_table": "qc_daily_incoming",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PDLSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sample_name", models.CharField(max_length=200)),
                ("pending", models.BooleanField(default=True)),
                ("remark", models.CharField(blank=True, max_length=300)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdl_samples",
                        to="QC.dailyqareport",
                    ),
                ),
            ],
            options={
                "db_table": "qc_daily_pdl_sample",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="QCInstrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("category", models.CharField(blank=True, max_length=60)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=250)),
            ],
            options={
                "db_table": "qc_instrument_master",
                "ordering": ["category", "name", "code"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="qc_instrume_is_acti_0e4019_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="dailyqareport",
            constraint=models.UniqueConstraint(
                fields=("report_date",), name="uq_daily_report_date"
            ),
        ),
        migrations.AddIndex(
            model_name="incomingmaterial",
            index=models.Index(
                fields=["material_type"], name="qc_daily_in_materia_7fa3fd_idx"
            ),
        ),
    ]
