# Generated by Django 5.0.11 on 2025-10-16 09:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QC", "0011_customercomplaint_analyticaldowntime_dailyqareport_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlfaProductMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alfa_name",
                    models.CharField(db_index=True, max_length=120, unique=True),
                ),
                ("finished_product_name", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "qc_alfa_product_master",
                "ordering": ["alfa_name"],
            },
        ),
        migrations.AddField(
            model_name="customercomplaint",
            name="finished_product_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name="Deviation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deviation_no",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("product", models.CharField(blank=True, max_length=200)),
                (
                    "finished_product",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("plant", models.CharField(blank=True, max_length=80)),
                ("batch_no", models.CharField(blank=True, max_length=60)),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Description of Deviation"
                    ),
                ),
                ("root_cause", models.TextField(blank=True, verbose_name="Root Cause")),
                ("corrective_action", models.TextField(blank=True)),
                ("preventive_action", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("progress", "In Progress"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "qc_deviation",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="qc_deviatio_status_441155_idx"
                    ),
                    models.Index(
                        fields=["product", "batch_no"],
                        name="qc_deviatio_product_3af209_idx",
                    ),
                ],
            },
        ),
    ]
