# Generated by Django 5.0.11 on 2025-10-17 05:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QC", "0012_alfaproductmaster_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticalMistake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("am_no", models.CharField(editable=False, max_length=30, unique=True)),
                (
                    "date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                ("product", models.CharField(blank=True, max_length=200)),
                ("finished_product", models.CharField(blank=True, max_length=200)),
                ("plant", models.CharField(blank=True, max_length=80)),
                ("batch_no", models.CharField(blank=True, max_length=60)),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Description of Analytical Mistake"
                    ),
                ),
                ("root_cause", models.TextField(blank=True, verbose_name="Root Cause")),
                ("corrective_action", models.TextField(blank=True)),
                ("preventive_action", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "qc_analytical_mistake",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(fields=["date"], name="qc_analytic_date_bb7eb8_idx"),
                    models.Index(fields=["plant"], name="qc_analytic_plant_73073f_idx"),
                    models.Index(
                        fields=["product", "batch_no"],
                        name="qc_analytic_product_a57c03_idx",
                    ),
                ],
            },
        ),
    ]
