# Generated by Django 5.0.11 on 2025-10-27 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QC", "0013_analyticalmistake"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="qcentry",
            index=models.Index(
                fields=["product", "batch_no"], name="qc_entry_product_659c30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qcentry",
            index=models.Index(
                fields=["product", "entry_date"], name="qc_entry_product_d4c9c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qcentry",
            index=models.Index(
                fields=["decision_status", "entry_date"],
                name="qc_entry_decisio_09e122_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="specentry",
            index=models.Index(
                fields=["qc_entry", "spec"], name="qc_spec_ent_qc_entr_fd583e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="specentry",
            index=models.Index(
                fields=["spec", "is_critical"], name="qc_spec_ent_spec_id_dc1ffa_idx"
            ),
        ),
    ]
