# Generated by Django 5.0.11 on 2025-10-30 07:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QC", "0014_qcentry_qc_entry_product_659c30_idx_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pdlsample",
            old_name="remark",
            new_name="remarks",
        ),
        migrations.RemoveField(
            model_name="pdlsample",
            name="pending",
        ),
        migrations.AddField(
            model_name="pdlsample",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pdlsample",
            name="result",
            field=models.CharField(
                choices=[
                    ("Pass", "Pass"),
                    ("Fail", "Fail"),
                    ("Hold", "Hold"),
                    ("NA", "N/A"),
                ],
                default="NA",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="pdlsample",
            name="stage",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="pdlsample",
            index=models.Index(
                fields=["report", "stage"], name="qc_daily_pd_report__ada06e_idx"
            ),
        ),
    ]
