# Generated by Django 5.0.11 on 2026-01-14 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QC", "0015_rename_remark_pdlsample_remarks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qcinstrument",
            name="instument_id",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="qcinstrument",
            name="category",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="qcinstrument",
            name="code",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="qcinstrument",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="qcinstrument",
            name="name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="qcinstrument",
            name="notes",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name="QCCalibrationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schedule_year",
                    models.CharField(
                        blank=True,
                        help_text="E.g. 2026-27",
                        max_length=15,
                        null=True,
                        verbose_name="Schedule Year",
                    ),
                ),
                ("calibration_date", models.DateField()),
                ("calibration_due_date", models.DateField()),
                ("reminder_date", models.DateField()),
                ("remarks", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calibration_schedules",
                        to="QC.qcinstrument",
                    ),
                ),
            ],
            options={
                "verbose_name": "QC Calibration Schedule",
                "verbose_name_plural": "QC Calibration Schedules",
                "db_table": "qc_calibration_schedule",
                "ordering": ["instrument__instument_id", "calibration_date"],
                "unique_together": {("instrument", "calibration_date")},
            },
        ),
    ]
