# Generated by Django 5.0.11 on 2026-02-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QC", "0016_qcinstrument_instument_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sampledescriptionoption",
            name="name",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name="sampledescriptionoption",
            index=models.Index(fields=["name"], name="sample_desc_name_3dc9a7_idx"),
        ),
    ]
