# Generated by Django 5.0.11 on 2026-02-06 10:15

import QC.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QC", "0017_alter_sampledescriptionoption_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FGProductQCStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Record Date"
                    ),
                ),
                (
                    "product",
                    models.CharField(max_length=200, verbose_name=QC.models.Product),
                ),
                (
                    "approved_qty",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Approved Qty",
                    ),
                ),
                (
                    "off_spec_qty",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Off Spec Qty",
                    ),
                ),
                (
                    "under_analysis",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Under Analysis Qty",
                    ),
                ),
                (
                    "total_qty",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        verbose_name="Total Qty",
                    ),
                ),
                ("remark", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "FG Product QC Status",
                "verbose_name_plural": "FG Product QC Statuses",
                "db_table": "fg_product_qc_status",
            },
        ),
        migrations.CreateModel(
            name="InstrumentOccupancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, default=datetime.date.today, verbose_name="Date"
                    ),
                ),
                ("area", models.CharField(max_length=50, verbose_name="Area")),
                ("make", models.CharField(max_length=100, verbose_name="Make")),
                ("model", models.CharField(max_length=100, verbose_name="Model")),
                (
                    "occupancy_percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Instrument occupancy in percent (0–100).",
                        max_digits=5,
                        verbose_name="% Occupancy",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, null=True, verbose_name="Remarks"),
                ),
            ],
            options={
                "verbose_name": "Instrument Occupancy",
                "verbose_name_plural": "Instrument Occupancies",
                "db_table": "instrument_occupancy",
                "ordering": ["area", "make", "model"],
            },
        ),
    ]
