# Generated by Django 5.0.11 on 2025-11-07 12:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockItemMaster",
            fields=[
                (
                    "product_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("item_type", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "blockitemmaster",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "eq_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("block", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Scheduler Equipment",
                "verbose_name_plural": "Scheduler Equipment",
                "db_table": "equipment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AssetsInventory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "row_flag",
                    models.CharField(
                        choices=[
                            ("OUTPUT", "WIP/SFG/FG/ Output"),
                            ("WIP", "WIP"),
                            ("EFFLUENT", "Effluent"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "batch_size",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("out_stage", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "out_item_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("out_bno", models.CharField(blank=True, max_length=100, null=True)),
                ("out_equip", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "out_b_starttime",
                    models.DateTimeField(blank=True, max_length=30, null=True),
                ),
                (
                    "out_b_endtime",
                    models.DateTimeField(blank=True, max_length=30, null=True),
                ),
                (
                    "out_bct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "out_qty",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("out_remarks", models.CharField(blank=True, max_length=200)),
                ("out_status", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "Asset / Inventory Row",
                "verbose_name_plural": "Asset / Inventory Rows",
                "db_table": "dc_assets_inventory",
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("display_name", models.CharField(max_length=60)),
            ],
            options={
                "verbose_name": "Block",
                "verbose_name_plural": "Blocks",
                "db_table": "dc_block",
            },
        ),
        migrations.CreateModel(
            name="ERPBOMDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage_name", models.CharField(max_length=200, unique=True)),
                ("fg_name", models.CharField(max_length=200)),
                ("equipment", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "ERP BOM Detail",
                "verbose_name_plural": "ERP BOM Details",
                "db_table": "daily_checks_erpbomdetail",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="BmrIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bmr_issue_type", models.CharField(max_length=50)),
                ("bmr_issue_no", models.CharField(max_length=50)),
                ("bmr_issue_date", models.DateField()),
                ("fg_name", models.CharField(max_length=200)),
                ("op_batch_no", models.CharField(db_index=True, max_length=100)),
                ("product_name", models.CharField(blank=True, max_length=200)),
                ("block", models.CharField(blank=True, max_length=100)),
                ("line_no", models.IntegerField()),
                ("item_type", models.CharField(max_length=100)),
                ("item_code", models.CharField(max_length=100)),
                ("item_name", models.CharField(max_length=200)),
                ("item_narration", models.TextField(blank=True)),
                ("uom", models.CharField(max_length=20)),
                (
                    "batch_quantity",
                    models.DecimalField(decimal_places=3, max_digits=18),
                ),
            ],
            options={
                "db_table": "bmr_issue",
                "managed": True,
                "unique_together": {("bmr_issue_no", "line_no")},
            },
        ),
        migrations.CreateModel(
            name="DailyCheckBOMEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment_type", models.CharField(blank=True, max_length=100)),
                ("moc", models.CharField(blank=True, max_length=100)),
                ("capacity", models.CharField(blank=True, max_length=50)),
                ("equipment_id", models.CharField(blank=True, max_length=100)),
                (
                    "std_bct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "wait_time",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("starttime", models.DateTimeField(blank=True, null=True)),
                ("endtime", models.DateTimeField(blank=True, null=True)),
                (
                    "actual_bct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "output_row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_equipment",
                        to="daily_block.assetsinventory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Check BOM Equipment",
                "verbose_name_plural": "Daily Check BOM Equipment",
                "db_table": "dc_bom_equipment",
            },
        ),
        migrations.CreateModel(
            name="DailyCheckBOMInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_category", models.CharField(blank=True, max_length=100)),
                ("material_name", models.CharField(blank=True, max_length=100)),
                (
                    "actual_qty",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "litre",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "density",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "ratio",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "output_row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_inputs",
                        to="daily_block.assetsinventory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Check BOM Input",
                "verbose_name_plural": "Daily Check BOM Inputs",
                "db_table": "dc_bom_inputs",
            },
        ),
        migrations.CreateModel(
            name="DailyCheckBOMOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_category", models.CharField(blank=True, max_length=100)),
                ("material_name", models.CharField(blank=True, max_length=100)),
                (
                    "actual_qty",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "litre",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "density",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "ratio",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "output_row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_outputs",
                        to="daily_block.assetsinventory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Check BOM Output",
                "verbose_name_plural": "Daily Check BOM Outputs",
                "db_table": "dc_bom_outputs",
            },
        ),
        migrations.CreateModel(
            name="DailyCheckBOMWaste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("waste_type", models.CharField(blank=True, max_length=100)),
                ("waste_name", models.CharField(blank=True, max_length=100)),
                (
                    "actual_qty",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "litre",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "density",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "ratio",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "output_row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_waste",
                        to="daily_block.assetsinventory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Check BOM Waste",
                "verbose_name_plural": "Daily Check BOM Wastes",
                "db_table": "dc_bom_waste",
            },
        ),
        migrations.CreateModel(
            name="DailyCheckHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_number",
                    models.CharField(blank=True, max_length=25, null=True, unique=True),
                ),
                ("report_dt", models.DateTimeField()),
                ("remarks", models.CharField(blank=True, max_length=500)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="daily_block.block",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Check Header",
                "verbose_name_plural": "Daily Check Headers",
                "db_table": "dc_daily_check_hdr",
                "ordering": ["-report_dt"],
            },
        ),
        migrations.AddField(
            model_name="assetsinventory",
            name="daily_check",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_rows",
                to="daily_block.dailycheckheader",
            ),
        ),
    ]
