# Generated by Django 5.0.11 on 2026-01-30 05:23

import ACCOUNTS.Budget.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("code", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="GLAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "no",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("unit", models.CharField(blank=True, default="", max_length=50)),
                (
                    "department",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "budget_head",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("blocked", models.BooleanField(default=False)),
                ("direct_posting", models.BooleanField(default=True)),
                ("last_date_modified", models.DateField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MakerCheckerState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                ("scope", models.CharField(blank=True, default="", max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("CHECKED", "Checked"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("checker_remarks", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "permissions": [
                    ("can_check_budgets", "Can check budgets"),
                    ("can_approve_budgets", "Can approve budgets"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductionBOM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fg_name", models.CharField(max_length=255, unique=True)),
                (
                    "fg_alpha_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "bom_code",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("fg_name",),
            },
        ),
        migrations.CreateModel(
            name="ProductionBOMEffluentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sr_no", models.PositiveIntegerField(default=0)),
                (
                    "waste_type",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "waste_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "waste_budget_norm",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=18
                    ),
                ),
                (
                    "waste_target_norm",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
            ],
            options={
                "ordering": ("sr_no", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProductionBOMInputLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sr_no", models.PositiveIntegerField(default=0)),
                (
                    "bom_item_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "material_category",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("material_name", models.CharField(max_length=255)),
                (
                    "budget_norm",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=18
                    ),
                ),
                (
                    "target_norm",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                ("unit", models.CharField(blank=True, default="", max_length=50)),
            ],
            options={
                "ordering": ("sr_no", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProductionBOMLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sr_no", models.PositiveIntegerField(default=0)),
                ("material_name", models.CharField(max_length=255)),
                (
                    "norm",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=12
                    ),
                ),
                (
                    "mat_qty_mt",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
            ],
            options={
                "ordering": ("sr_no", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProductionBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "apr",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=14
                    ),
                ),
                (
                    "may",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=14
                    ),
                ),
                (
                    "jun",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=14
                    ),
                ),
                (
                    "jul",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=14
                    ),
                ),
                (
                    "aug",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=14
                    ),
                ),
                (
                    "sep",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=14
                    ),
                ),
                (
                    "oct",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=14
                    ),
                ),
                (
                    "nov",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=14
                    ),
                ),
                (
                    "dec",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=14
                    ),
                ),
                (
                    "jan",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=14
                    ),
                ),
                (
                    "feb",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=14
                    ),
                ),
                (
                    "mar",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=14
                    ),
                ),
                (
                    "total_fg_qty",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=16
                    ),
                ),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="ProductionBudgetFG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fg_name", models.CharField(max_length=255)),
                (
                    "apr",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=18
                    ),
                ),
                (
                    "may",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=18
                    ),
                ),
                (
                    "jun",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=18
                    ),
                ),
                (
                    "jul",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=18
                    ),
                ),
                (
                    "aug",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=18
                    ),
                ),
                (
                    "sep",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=18
                    ),
                ),
                (
                    "oct",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=18
                    ),
                ),
                (
                    "nov",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=18
                    ),
                ),
                (
                    "dec",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=18
                    ),
                ),
                (
                    "jan",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=18
                    ),
                ),
                (
                    "feb",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=18
                    ),
                ),
                (
                    "mar",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=18
                    ),
                ),
                (
                    "total_fg_qty",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=20
                    ),
                ),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductionBudgetFGLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sr_no", models.PositiveIntegerField(default=0)),
                (
                    "bom_item_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("material_name", models.CharField(max_length=255)),
                ("unit", models.CharField(blank=True, default="", max_length=100)),
                (
                    "norm",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=18
                    ),
                ),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "ordering": ("sr_no", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProductionBudgetLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sr_no", models.PositiveIntegerField(default=0)),
                ("material_name", models.CharField(max_length=255)),
                (
                    "norm",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=12
                    ),
                ),
                (
                    "target_norm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Manual target norm (no correlation / calculation).",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "ordering": ("sr_no", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProductionNorm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fg_name", models.CharField(max_length=255)),
                (
                    "bom_item_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("is_captive", models.BooleanField(default=False)),
                ("bom_item_name", models.CharField(max_length=255)),
                ("unit", models.CharField(blank=True, default="", max_length=100)),
                (
                    "norm",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=18
                    ),
                ),
                (
                    "target_norm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Manual target norm for budgeting reference (does not affect calculations).",
                        max_digits=18,
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RMCBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usd_inr",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("86.0000"), max_digits=12
                    ),
                ),
                ("selected_fgs", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RMCBudgetLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rm_code", models.CharField(max_length=60)),
                ("rm_name", models.CharField(max_length=255)),
                (
                    "required_qty",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=20
                    ),
                ),
                ("unit", models.CharField(blank=True, default="", max_length=50)),
                (
                    "purchase_type",
                    models.CharField(
                        choices=[
                            ("LOCAL", "Local Purchase"),
                            ("IMPORT", "Import Purchase"),
                        ],
                        default="LOCAL",
                        max_length=10,
                    ),
                ),
                (
                    "local_rate_inr",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "import_rate_usd",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "duty_percent",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=10
                    ),
                ),
                (
                    "freight_inr",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=18
                    ),
                ),
                (
                    "clearance_inr",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=18
                    ),
                ),
                (
                    "qty_apr",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=20
                    ),
                ),
                (
                    "qty_may",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=20
                    ),
                ),
                (
                    "qty_jun",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=20
                    ),
                ),
                (
                    "qty_jul",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=20
                    ),
                ),
                (
                    "qty_aug",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=20
                    ),
                ),
                (
                    "qty_sep",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=20
                    ),
                ),
                (
                    "qty_oct",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=20
                    ),
                ),
                (
                    "qty_nov",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=20
                    ),
                ),
                (
                    "qty_dec",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=20
                    ),
                ),
                (
                    "qty_jan",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=20
                    ),
                ),
                (
                    "qty_feb",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=20
                    ),
                ),
                (
                    "qty_mar",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=20
                    ),
                ),
                (
                    "total_qty",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=22
                    ),
                ),
                (
                    "budget_rate_inr",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=18
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("rm_name", "id"),
            },
        ),
        migrations.CreateModel(
            name="SalesBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inr_usd",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("86.00"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SalesBudgetLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                (
                    "sale_type",
                    models.CharField(
                        choices=[("DOMESTIC", "DOMESTIC"), ("EXPORT", "EXPORT")],
                        default="DOMESTIC",
                        max_length=20,
                    ),
                ),
                (
                    "annual_qty_mt",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=18
                    ),
                ),
                (
                    "rate_usd",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "rate_inr",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "amt_inr",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=20
                    ),
                ),
                (
                    "amt_inr_cr",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=20
                    ),
                ),
                (
                    "apr",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=18
                    ),
                ),
                (
                    "may",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=18
                    ),
                ),
                (
                    "jun",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=18
                    ),
                ),
                (
                    "jul",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=18
                    ),
                ),
                (
                    "aug",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=18
                    ),
                ),
                (
                    "sep",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=18
                    ),
                ),
                (
                    "oct",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=18
                    ),
                ),
                (
                    "nov",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=18
                    ),
                ),
                (
                    "dec",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=18
                    ),
                ),
                (
                    "jan",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=18
                    ),
                ),
                (
                    "feb",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=18
                    ),
                ),
                (
                    "mar",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=18
                    ),
                ),
                (
                    "total_month_qty",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=20
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("code", models.CharField(max_length=30, unique=True)),
                (
                    "default_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_categories",
                        to="Budget.accountgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountSubcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(max_length=30)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="Budget.accountcategory",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subcategories",
                        to="Budget.accountgroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BudgetLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("safety", "Safety & Health"),
                            ("environment", "Environment"),
                            ("qaqc", "QA& QC"),
                            ("engineering", "Engineering"),
                            ("utility", "Utility"),
                            ("admin", "Admin"),
                            ("hr", "HR"),
                            ("rd", "R&D"),
                            ("logistic", "Logistic"),
                            ("fin_accounts", "Finance & Accounts"),
                            ("steam", "Steam (Legacy)"),
                            ("electricity", "Electricity (Legacy)"),
                            ("rm", "R & M (Legacy)"),
                            ("emp_oc", "Employee Cost (OC) (Legacy)"),
                            (
                                "emp_contract",
                                "Employee Cost (Contract Employees) (Legacy)",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                ("sr_no", models.PositiveIntegerField(default=0)),
                ("particulars", models.CharField(max_length=255)),
                (
                    "prev_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "prev_actual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "apr",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "may",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "jun",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "jul",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "aug",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "sep",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "oct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "nov",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "dec",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "jan",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "feb",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "mar",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=16
                    ),
                ),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="budgets/line_attachments/"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_lines",
                        to="Budget.accountcategory",
                    ),
                ),
                (
                    "account_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_lines",
                        to="Budget.accountgroup",
                    ),
                ),
            ],
            options={
                "ordering": ("sr_no", "id"),
            },
        ),
        migrations.CreateModel(
            name="BudgetLineAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=ACCOUNTS.Budget.models.budget_line_attachment_path
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=150)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="Budget.budgetline",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_line_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-uploaded_at",),
            },
        ),
        migrations.CreateModel(
            name="BudgetPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fy", models.CharField(max_length=7)),
                (
                    "company_group",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-fy", "-updated_at"),
            },
        ),
        migrations.AddField(
            model_name="budgetline",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="Budget.budgetplan",
            ),
        ),
        migrations.CreateModel(
            name="CaptiveConsumptionBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="captive_budgets_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="captive_budgets",
                        to="Budget.budgetplan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="captive_budgets_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Budget_captiveconsumptionbudget",
                "ordering": ("-updated_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="CaptiveConsumptionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=255)),
                (
                    "captive_type",
                    models.CharField(
                        choices=[
                            ("CAPTIVE", "Captive"),
                            ("TRIAL", "Trial"),
                            ("SAMPLE", "Sample"),
                            ("INTERNAL", "Internal"),
                        ],
                        default="CAPTIVE",
                        max_length=30,
                    ),
                ),
                (
                    "qty",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=14
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=14
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="Budget.captiveconsumptionbudget",
                    ),
                ),
            ],
            options={
                "db_table": "Budget_captiveconsumptionline",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="DepartmentBudgetHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit", models.CharField(blank=True, default="", max_length=50)),
                ("department", models.CharField(max_length=120)),
                ("budget_head", models.CharField(max_length=255)),
                ("gl", models.CharField(blank=True, default="", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dept_budget_heads_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dept_budget_heads_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ERPBOMRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sr_no", models.BigIntegerField(blank=True, null=True)),
                ("bom_id", models.BigIntegerField(blank=True, null=True)),
                ("seq_id", models.BigIntegerField(blank=True, null=True)),
                ("cflag", models.CharField(blank=True, default="", max_length=5)),
                ("itm_type", models.CharField(blank=True, default="", max_length=100)),
                ("item_name", models.CharField(blank=True, default="", max_length=255)),
                ("fg_name", models.CharField(blank=True, default="", max_length=255)),
                ("item_code", models.CharField(blank=True, default="", max_length=100)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                ("bom_code", models.CharField(blank=True, default="", max_length=100)),
                ("bom_name", models.CharField(blank=True, default="", max_length=255)),
                ("based_on", models.CharField(blank=True, default="", max_length=20)),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "bom_cnv",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                ("type", models.CharField(blank=True, default="", max_length=100)),
                (
                    "bom_item_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "bom_item_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("unit", models.CharField(blank=True, default="", max_length=100)),
                (
                    "bom_qty",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "stock_parameter",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("snapshot_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_db",
                    models.CharField(
                        blank=True, default="eresOCSPL_Test", max_length=100
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["fg_name"], name="Budget_erpb_fg_name_a54198_idx"
                    ),
                    models.Index(fields=["type"], name="Budget_erpb_type_443ea8_idx"),
                    models.Index(
                        fields=["bom_code"], name="Budget_erpb_bom_cod_1c7e44_idx"
                    ),
                    models.Index(
                        fields=["bom_item_code"], name="Budget_erpb_bom_ite_9aaa48_idx"
                    ),
                    models.Index(
                        fields=["bom_id"], name="Budget_erpb_bom_id_538b21_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="erpbomrow",
            constraint=models.UniqueConstraint(
                fields=("bom_id", "seq_id", "bom_item_code", "fg_name", "type"),
                name="uq_erp_bom_row",
            ),
        ),
        migrations.AddField(
            model_name="glaccount",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_gl_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="budgetline",
            name="gl_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budget_lines",
                to="Budget.glaccount",
            ),
        ),
        migrations.AddField(
            model_name="makercheckerstate",
            name="checked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mc_checked_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="makercheckerstate",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="makercheckerstate",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mc_submitted_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productionbom",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prod_boms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productionbomeffluentline",
            name="bom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="effluent_lines",
                to="Budget.productionbom",
            ),
        ),
        migrations.AddField(
            model_name="productionbominputline",
            name="bom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="input_lines",
                to="Budget.productionbom",
            ),
        ),
        migrations.AddField(
            model_name="productionbomline",
            name="bom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="Budget.productionbom",
            ),
        ),
        migrations.AddField(
            model_name="productionbudget",
            name="bom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budgets",
                to="Budget.productionbom",
            ),
        ),
        migrations.AddField(
            model_name="productionbudget",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="production_budgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productionbudget",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_budgets",
                to="Budget.budgetplan",
            ),
        ),
        migrations.AddField(
            model_name="productionbudgetfg",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prod_fg_budgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productionbudgetfg",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_fg_budgets",
                to="Budget.budgetplan",
            ),
        ),
        migrations.AddField(
            model_name="productionbudgetfgline",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="Budget.productionbudgetfg",
            ),
        ),
        migrations.AddField(
            model_name="productionbudgetline",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="Budget.productionbudget",
            ),
        ),
        migrations.AddField(
            model_name="productionnorm",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rmcbudget",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rmc_budgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rmcbudget",
            name="plan",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rmc_budget",
                to="Budget.budgetplan",
            ),
        ),
        migrations.AddField(
            model_name="rmcbudgetline",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="Budget.rmcbudget",
            ),
        ),
        migrations.AddField(
            model_name="salesbudget",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salesbudget",
            name="plan",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_budget",
                to="Budget.budgetplan",
            ),
        ),
        migrations.AddField(
            model_name="salesbudgetline",
            name="budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="Budget.salesbudget",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="accountsubcategory",
            unique_together={("category", "code")},
        ),
        migrations.AddIndex(
            model_name="budgetlineattachment",
            index=models.Index(
                fields=["line", "uploaded_at"], name="Budget_budg_line_id_218bf4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="budgetplan",
            unique_together={("fy", "company_group")},
        ),
        migrations.AddIndex(
            model_name="departmentbudgethead",
            index=models.Index(
                fields=["department", "unit"], name="Budget_depa_departm_d1510c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="departmentbudgethead",
            index=models.Index(
                fields=["budget_head"], name="Budget_depa_budget__7316d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="departmentbudgethead",
            index=models.Index(fields=["gl"], name="Budget_depa_gl_e0b0e4_idx"),
        ),
        migrations.AddConstraint(
            model_name="departmentbudgethead",
            constraint=models.UniqueConstraint(
                fields=("unit", "department", "budget_head"),
                name="uq_dept_budget_head_unit_dept_head",
            ),
        ),
        migrations.AddIndex(
            model_name="glaccount",
            index=models.Index(
                fields=["department", "unit"], name="Budget_glac_departm_acc3be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="glaccount",
            index=models.Index(
                fields=["department", "unit", "budget_head"],
                name="Budget_glac_departm_abe8d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="glaccount",
            index=models.Index(fields=["name"], name="Budget_glac_name_0a05ba_idx"),
        ),
        migrations.AddIndex(
            model_name="glaccount",
            index=models.Index(fields=["no"], name="Budget_glac_no_344320_idx"),
        ),
        migrations.AddConstraint(
            model_name="glaccount",
            constraint=models.UniqueConstraint(
                fields=("unit", "department", "budget_head", "name"),
                name="uq_gl_unit_dept_head_name",
            ),
        ),
        migrations.AddIndex(
            model_name="budgetline",
            index=models.Index(
                fields=["plan", "category"], name="Budget_budg_plan_id_4dc983_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budgetline",
            index=models.Index(
                fields=["plan", "category", "account_group"],
                name="Budget_budg_plan_id_326fc5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="budgetline",
            index=models.Index(
                fields=["gl_account"], name="Budget_budg_gl_acco_754117_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="makercheckerstate",
            index=models.Index(
                fields=["scope", "status"], name="Budget_make_scope_b2b391_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="makercheckerstate",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_id", "scope"),
                name="uq_mc_state_object_scope",
            ),
        ),
        migrations.AddIndex(
            model_name="productionbomeffluentline",
            index=models.Index(fields=["bom"], name="Budget_prod_bom_id_8b5002_idx"),
        ),
        migrations.AddIndex(
            model_name="productionbominputline",
            index=models.Index(fields=["bom"], name="Budget_prod_bom_id_976b58_idx"),
        ),
        migrations.AddIndex(
            model_name="productionbomline",
            index=models.Index(fields=["bom"], name="Budget_prod_bom_id_f51776_idx"),
        ),
        migrations.AddIndex(
            model_name="productionbudget",
            index=models.Index(
                fields=["plan", "bom"], name="Budget_prod_plan_id_cc5a0a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productionbudget",
            unique_together={("plan", "bom")},
        ),
        migrations.AddIndex(
            model_name="productionbudgetfg",
            index=models.Index(
                fields=["plan", "fg_name"], name="Budget_prod_plan_id_e67a90_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productionbudgetfg",
            unique_together={("plan", "fg_name")},
        ),
        migrations.AddIndex(
            model_name="productionbudgetfgline",
            index=models.Index(
                fields=["budget"], name="Budget_prod_budget__ba2f67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionbudgetfgline",
            index=models.Index(
                fields=["bom_item_code"], name="Budget_prod_bom_ite_3c55d9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productionbudgetfgline",
            constraint=models.UniqueConstraint(
                fields=("budget", "bom_item_code"),
                name="uq_prod_budget_fg_line_budget_item",
            ),
        ),
        migrations.AddIndex(
            model_name="productionbudgetline",
            index=models.Index(
                fields=["budget"], name="Budget_prod_budget__79e14c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionnorm",
            index=models.Index(
                fields=["fg_name"], name="Budget_prod_fg_name_7d0c3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionnorm",
            index=models.Index(
                fields=["bom_item_code"], name="Budget_prod_bom_ite_ae907e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productionnorm",
            constraint=models.UniqueConstraint(
                fields=("fg_name", "bom_item_code"), name="uq_prod_norm_fg_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="rmcbudgetline",
            constraint=models.UniqueConstraint(
                fields=("budget", "rm_code"), name="uq_rmc_budget_rm_code"
            ),
        ),
        migrations.AddIndex(
            model_name="salesbudgetline",
            index=models.Index(
                fields=["product_name"], name="Budget_sale_product_e87aca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesbudgetline",
            index=models.Index(
                fields=["sale_type"], name="Budget_sale_sale_ty_9f9424_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="salesbudgetline",
            constraint=models.UniqueConstraint(
                fields=("budget", "product_name", "sale_type"),
                name="uq_sales_budget_product",
            ),
        ),
    ]
