# Generated by Django 5.0.11 on 2026-02-04 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Budget", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rmcbudgetline",
            name="uq_rmc_budget_rm_code",
        ),
        migrations.RemoveIndex(
            model_name="productionnorm",
            name="Budget_prod_fg_name_7d0c3b_idx",
        ),
        migrations.RemoveIndex(
            model_name="productionnorm",
            name="Budget_prod_bom_ite_ae907e_idx",
        ),
        migrations.AddField(
            model_name="productionbominputline",
            name="is_captive",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="rmcbudgetline",
            name="is_captive",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="productionnorm",
            name="bom_item_code",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="productionnorm",
            name="fg_name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="productionnorm",
            name="is_captive",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="productionbominputline",
            index=models.Index(
                fields=["bom", "bom_item_code"], name="Budget_prod_bom_id_ff5738_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionbominputline",
            index=models.Index(
                fields=["bom", "is_captive"], name="Budget_prod_bom_id_575267_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionnorm",
            index=models.Index(
                fields=["fg_name", "bom_item_code"],
                name="Budget_prod_fg_name_e4a298_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productionnorm",
            index=models.Index(
                fields=["fg_name", "is_captive"], name="Budget_prod_fg_name_28d599_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rmcbudgetline",
            constraint=models.UniqueConstraint(
                fields=("budget", "rm_code", "is_captive"),
                name="uq_rmc_budget_rm_code_captive",
            ),
        ),
    ]
