# Generated by Django 5.0.11 on 2026-02-07 07:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Budget", "0002_remove_rmcbudgetline_uq_rmc_budget_rm_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionBudgetFGEffluentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sr_no", models.PositiveIntegerField(default=0)),
                (
                    "waste_type",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "waste_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "waste_norm",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=18
                    ),
                ),
                (
                    "waste_target_norm",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "qty_apr",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=18
                    ),
                ),
                (
                    "qty_may",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=18
                    ),
                ),
                (
                    "qty_jun",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=18
                    ),
                ),
                (
                    "qty_jul",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=18
                    ),
                ),
                (
                    "qty_aug",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=18
                    ),
                ),
                (
                    "qty_sep",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=18
                    ),
                ),
                (
                    "qty_oct",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=18
                    ),
                ),
                (
                    "qty_nov",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=18
                    ),
                ),
                (
                    "qty_dec",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=18
                    ),
                ),
                (
                    "qty_jan",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=18
                    ),
                ),
                (
                    "qty_feb",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=18
                    ),
                ),
                (
                    "qty_mar",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=18
                    ),
                ),
                (
                    "waste_qty_year",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=18
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effluent_lines",
                        to="Budget.productionbudgetfg",
                    ),
                ),
            ],
            options={
                "ordering": ("sr_no", "id"),
                "indexes": [
                    models.Index(
                        fields=["budget"], name="Budget_prod_budget__ac9aef_idx"
                    ),
                    models.Index(
                        fields=["budget", "sr_no"],
                        name="Budget_prod_budget__74b397_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="productionbudgetfgeffluentline",
            constraint=models.UniqueConstraint(
                fields=("budget", "sr_no", "waste_type", "waste_name"),
                name="uq_prod_budget_fg_effluent",
            ),
        ),
    ]
