# Generated by Django 5.0.11 on 2026-02-17 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Budget", "0003_productionbudgetfgeffluentline_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetline",
            name="category",
            field=models.CharField(
                choices=[
                    ("production", "Production"),
                    ("safety", "Safety & Health"),
                    ("environment", "Environment"),
                    ("qaqc", "QA& QC"),
                    ("engineering", "Engineering"),
                    ("utility", "Utility"),
                    ("admin", "Admin"),
                    ("hr", "HR"),
                    ("rd", "R&D"),
                    ("logistic", "Logistic"),
                    ("fin_accounts", "Finance & Accounts"),
                    ("sales", "Sales"),
                    ("steam", "Steam (Legacy)"),
                    ("electricity", "Electricity (Legacy)"),
                    ("rm", "R & M (Legacy)"),
                    ("emp_oc", "Employee Cost (OC) (Legacy)"),
                    ("emp_contract", "Employee Cost (Contract Employees) (Legacy)"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="UserBudgetCategoryAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("production", "Production"),
                            ("safety", "Safety & Health"),
                            ("environment", "Environment"),
                            ("qaqc", "QA& QC"),
                            ("engineering", "Engineering"),
                            ("utility", "Utility"),
                            ("admin", "Admin"),
                            ("hr", "HR"),
                            ("rd", "R&D"),
                            ("logistic", "Logistic"),
                            ("fin_accounts", "Finance & Accounts"),
                            ("sales", "Sales"),
                            ("steam", "Steam (Legacy)"),
                            ("electricity", "Electricity (Legacy)"),
                            ("rm", "R & M (Legacy)"),
                            ("emp_oc", "Employee Cost (OC) (Legacy)"),
                            (
                                "emp_contract",
                                "Employee Cost (Contract Employees) (Legacy)",
                            ),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("can_view", models.BooleanField(default=True)),
                ("can_edit", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_category_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "category"],
                        name="Budget_user_user_id_ae0a01_idx",
                    )
                ],
                "unique_together": {("user", "category")},
            },
        ),
    ]
