# Generated by Django 5.0.11 on 2026-03-09 11:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Budget", "0004_alter_budgetline_category_userbudgetcategoryaccess"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PackingBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_products", models.JSONField(blank=True, default=list)),
                (
                    "wastage_percent_default",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10.00"), max_digits=6
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packing_budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packing_budget",
                        to="Budget.budgetplan",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="PackingMaterialMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_code",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("item_name", models.CharField(max_length=255)),
                ("unit", models.CharField(blank=True, default="", max_length=50)),
                (
                    "packing_size",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=18, null=True
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("item_name", "item_code"),
            },
        ),
        migrations.CreateModel(
            name="PackingBudgetLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(db_index=True, max_length=255)),
                (
                    "packing_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "packing_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("unit", models.CharField(blank=True, default="", max_length=50)),
                (
                    "packing_size",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=18, null=True
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "wastage_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10.00"), max_digits=6
                    ),
                ),
                (
                    "req_apr",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=24
                    ),
                ),
                (
                    "req_may",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=24
                    ),
                ),
                (
                    "req_jun",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=24
                    ),
                ),
                (
                    "req_jul",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=24
                    ),
                ),
                (
                    "req_aug",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=24
                    ),
                ),
                (
                    "req_sep",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=24
                    ),
                ),
                (
                    "req_oct",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=24
                    ),
                ),
                (
                    "req_nov",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=24
                    ),
                ),
                (
                    "req_dec",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=24
                    ),
                ),
                (
                    "req_jan",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=24
                    ),
                ),
                (
                    "req_feb",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=24
                    ),
                ),
                (
                    "req_mar",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=24
                    ),
                ),
                (
                    "req_total",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=24
                    ),
                ),
                (
                    "val_apr",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=24
                    ),
                ),
                (
                    "val_may",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=24
                    ),
                ),
                (
                    "val_jun",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=24
                    ),
                ),
                (
                    "val_jul",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=24
                    ),
                ),
                (
                    "val_aug",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=24
                    ),
                ),
                (
                    "val_sep",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=24
                    ),
                ),
                (
                    "val_oct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=24
                    ),
                ),
                (
                    "val_nov",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=24
                    ),
                ),
                (
                    "val_dec",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=24
                    ),
                ),
                (
                    "val_jan",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=24
                    ),
                ),
                (
                    "val_feb",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=24
                    ),
                ),
                (
                    "val_mar",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=24
                    ),
                ),
                (
                    "val_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=24
                    ),
                ),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="Budget.packingbudget",
                    ),
                ),
                (
                    "packing_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budget_lines",
                        to="Budget.packingmaterialmaster",
                    ),
                ),
            ],
            options={
                "ordering": ("product_name", "packing_name", "packing_code", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="packingmaterialmaster",
            index=models.Index(
                fields=["item_name"], name="Budget_pack_item_na_1f1b71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="packingmaterialmaster",
            index=models.Index(
                fields=["is_active"], name="Budget_pack_is_acti_1ffe06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="packingbudgetline",
            index=models.Index(
                fields=["budget", "product_name"], name="Budget_pack_budget__5899df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="packingbudgetline",
            index=models.Index(
                fields=["budget", "packing_code"], name="Budget_pack_budget__0e49fd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="packingbudgetline",
            constraint=models.UniqueConstraint(
                fields=("budget", "product_name", "packing_material"),
                name="uq_packing_budget_product_material",
            ),
        ),
    ]
