# Generated by Django 5.0.11 on 2025-09-25 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment_id", models.CharField(db_index=True, max_length=50)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("scheduled_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("DONE", "Done"),
                            ("POSTPONED", "Postponed/Rescheduled"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "downtime_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total downtime in minutes (if any)",
                        null=True,
                    ),
                ),
                ("downtime_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "rescheduled_to",
                    models.DateField(
                        blank=True, help_text="New date if postponed", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_completed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "maintenance_schedule",
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_date"],
                        name="maintenance_status_b40001_idx",
                    )
                ],
                "unique_together": {("equipment_id", "scheduled_date")},
            },
        ),
    ]
