# Generated by Django 5.0.11 on 2025-07-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HR_BUDGET", "0002_hrbudgetlegal_alter_hrbudgetamc_amc_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractorwages",
            name="total_bill_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="hrbudgetcanteen",
            name="total_bill_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="hrbudgetmedical",
            name="total_bill_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="hrbudgetvehicle",
            name="total_bill_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="hrbudgetwelfare",
            name="total_bill_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="securitywages",
            name="total_bill_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterModelTable(
            name="contractorwages",
            table="contractor_wages",
        ),
        migrations.AlterModelTable(
            name="securitywages",
            table="security_wages",
        ),
    ]
