# Generated by Django 5.0.11 on 2025-07-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HR_BUDGET", "0003_contractorwages_total_bill_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminCapex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_date", models.DateField()),
                ("invoice_no", models.CharField(blank=True, max_length=50, null=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "gst",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "bill_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "total_bill_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Admin Capex",
                "verbose_name_plural": "Admin Capex",
                "db_table": "admin_capex",
            },
        ),
        migrations.CreateModel(
            name="AdminRepairAndMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_date", models.DateField()),
                ("invoice_no", models.CharField(blank=True, max_length=50, null=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "gst",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "bill_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "total_bill_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Admin Repair and Maintenance",
                "verbose_name_plural": "Admin Repair and Maintenance",
                "db_table": "admin_repair_and_maintenance",
            },
        ),
        migrations.AddField(
            model_name="hrbudgetamc",
            name="total_bill_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="hrbudgetcommunication",
            name="total_bill_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="hrbudgetgeneraladmin",
            name="total_bill_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="hrbudgetguesthouse",
            name="total_bill_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="hrbudgetlegal",
            name="total_bill_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="hrbudgettraining",
            name="total_bill_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="hrbudgettravellinglodging",
            name="total_bill_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="insurancemediclaim",
            name="total_bill_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hrbudgetgeneraladmin",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Printing", "Printing"),
                    ("Stationary", "Stationary"),
                    ("Cleaning Material", "Cleaning Material"),
                    ("Harshada Courier Services", "Harshada Courier Services"),
                    ("Courier (Sample to Vasai)", "Courier (Sample to Vasai)"),
                    ("Pest Control", "Pest Control"),
                    (
                        "Sunshine Services Xerox Conon E-16 Admin",
                        "Sunshine Services Xerox Conon E-16 Admin",
                    ),
                    (
                        "Sunshine Services Xerox Conon QC Lab",
                        "Sunshine Services Xerox Conon QC Lab",
                    ),
                    (
                        "Sunshine Services Xerox Conon E-18 Admin",
                        "Sunshine Services Xerox Conon E-18 Admin",
                    ),
                    (
                        "Sunshine Services Xerox Conon E-17 Admin",
                        "Sunshine Services Xerox Conon E-17 Admin",
                    ),
                    ("Fridge repairing", "Fridge repairing"),
                    ("Water bottle", "Water bottle"),
                    ("Aquaguard/RO", "Aquaguard/RO"),
                    (
                        "Balanand Kirana / Shri Datta Kirana (Jagerry)",
                        "Balanand Kirana / Shri Datta Kirana (Jagerry)",
                    ),
                    ("Pantry", "Pantry"),
                    ("Conveyance", "Conveyance"),
                    ("Post Office", "Post Office"),
                    ("Night round police", "Night round police"),
                    ("Air Conditioner - Services", "Air Conditioner - Services"),
                    ("Furniture", "Furniture"),
                    ("Mahi Jal", "Mahi Jal"),
                    ("Other", "Other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hrbudgettravellinglodging",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Vaishnavi/Raghvendra/Darshan Tours & Travels",
                        "Vaishnavi/Raghvendra/Darshan Tours & Travels",
                    ),
                    ("Balaji Sarovar Premire", "Balaji Sarovar Premire"),
                    ("Hotel Lotus", "Hotel Lotus"),
                    ("Hotel Kyriad", "Hotel Kyriad"),
                    ("Hotel Sai Prasad Executive", "Hotel Sai Prasad Executive"),
                    ("Other", "Other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
