# Generated by Django 5.0.11 on 2025-08-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HR_BUDGET", "0004_admincapex_adminrepairandmaintenance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hrbudgetwelfare",
            name="welfare_name",
            field=models.CharField(
                choices=[
                    ("Uniform", "Uniform"),
                    ("Employee Engagement", "Employee Engagement"),
                    ("Open house meeting", "Open house meeting"),
                    ("DiwaliSweets", "DiwaliSweets"),
                    ("Other", "Other"),
                ],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="HRBudgetPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(help_text="Eg. 2025-26", max_length=9)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Contractor Wages", "Contractor Wages"),
                            ("Security Wages", "Security Wages"),
                            ("Welfare", "Welfare"),
                            ("Canteen", "Canteen"),
                            ("Medical Expenses", "Medical Expenses"),
                            ("Vehicle Expenses", "Vehicle Expenses"),
                            ("Travelling & Lodging", "Travelling & Lodging"),
                            ("Guest House Expenses", "Guest House Expenses"),
                            ("General Admin Expenses", "General Admin Expenses"),
                            ("Communication Expenses", "Communication Expenses"),
                            ("Insurance Mediclaim", "Insurance Mediclaim"),
                            ("AMC", "AMC"),
                            ("Training", "Training"),
                            ("Legal", "Legal"),
                            (
                                "Admin Repair & Maintenance",
                                "Admin Repair & Maintenance",
                            ),
                            ("Admin Capex", "Admin Capex"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "plan_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Enter amount..", max_digits=12
                    ),
                ),
            ],
            options={
                "db_table": "hrbudget_plan",
                "unique_together": {("year", "category")},
            },
        ),
    ]
