# Generated by Django 5.0.11 on 2025-12-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HR_BUDGET", "0005_alter_hrbudgetwelfare_welfare_name_hrbudgetplan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hrbudgetcanteen",
            name="name",
            field=models.CharField(
                choices=[
                    ("Balaji Tea Corner", "Balaji Tea Corner"),
                    ("Dayanand Mhetre", "Dayanand Mhetre"),
                    ("Ambai Pure Wage", "Ambai Pure Wage"),
                    ("Tea & Biscuit", "Tea & Biscuit"),
                    ("Other", "Other"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="hrbudgetguesthouse",
            name="category",
            field=models.CharField(
                choices=[
                    ("Rent", "Rent"),
                    ("Maintenance", "Maintenance"),
                    (
                        "Grocery/Vegetables/Milk/Curd/Laundary",
                        "Grocery/Vegetables/Milk/Curd/Laundary",
                    ),
                    ("A/c Servicing", "A/c Servicing"),
                    ("Cleaning Boy", "Cleaning Boy"),
                    ("DISH Recharge", "DISH Recharge"),
                    ("House Keeping", "House Keeping"),
                    ("Light bill", "Light bill"),
                    ("Guest House Cook", "Guest House Cook"),
                    ("Other", "Other"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="hrbudgetmedical",
            name="doctor_hospital_name",
            field=models.CharField(
                choices=[
                    ("Dr. Ganesh Atwade(FMO)", "Dr. Ganesh Atwade(FMO)"),
                    ("Baladava Hospital", "Baladava Hospital"),
                    ("Dr. Chidgupkar Hospital", "Dr. Chidgupkar Hospital"),
                    ("Shilpakaya Hospital", "Shilpakaya Hospital"),
                    ("Doctor Ukarande", "Doctor Ukarande"),
                    ("Medicines for OHC", "Medicines for OHC"),
                    ("New joinee health check up", "New joinee health check up"),
                    ("Annual Health Check up", "Annual Health Check up"),
                    ("Other", "Other"),
                ],
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="hrbudgetplan",
            name="category",
            field=models.CharField(
                choices=[
                    ("Contractor Wages", "Contractor Wages"),
                    ("Security Wages", "Security Wages"),
                    ("Welfare", "Welfare"),
                    ("Canteen", "Canteen"),
                    ("Medical Expenses", "Medical Expenses"),
                    ("Vehicle Expenses", "Vehicle Expenses"),
                    ("Travelling & Lodging", "Travelling & Lodging"),
                    ("Guest House Expenses", "Guest House Expenses"),
                    ("General Admin Expenses", "General Admin Expenses"),
                    ("Communication Expenses", "Communication Expenses"),
                    ("Insurance Mediclaim", "Insurance Mediclaim"),
                    ("AMC", "AMC"),
                    ("Training", "Training"),
                    ("Legal", "Legal"),
                    ("Admin Repair & Maintenance", "Admin Repair & Maintenance"),
                    ("Admin Capex", "Admin Capex"),
                    ("Other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="hrbudgetvehicle",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Daily Pickup-drop", "Daily Pickup-drop"),
                    ("Fuel expense", "Fuel expense"),
                    ("Insurance", "Insurance"),
                    ("Repair & Maintenance", "Repair & Maintenance"),
                    ("Material / Goods", "Material / Goods"),
                    ("Other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="insurancemediclaim",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Insurance Mediclaim GMP", "Insurance Mediclaim GMP"),
                    ("GPAP", "GPAP"),
                    ("WC Policy", "WC Policy"),
                    ("Other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
