# Generated by Django 5.0.11 on 2025-08-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UTILITY", "0002_utilitypowerreading"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilityrecord",
            name="briquette_tfh",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
