# Generated by Django 5.0.11 on 2025-12-30 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualPayableEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("specialities", "OC Specialities Private Limited"),
                            ("chemicals", "OC Specialities Chemicals Private Limited"),
                        ],
                        help_text="Optional: link to cashflow Company Group filter",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "nature",
                    models.CharField(
                        choices=[
                            (
                                "ADVANCE PAYMENT - CAPEX/RM",
                                "ADVANCE PAYMENT - CAPEX/RM",
                            ),
                            ("SALARY & WAGES", "SALARY & WAGES"),
                            ("BONUS", "BONUS"),
                            (
                                "PAYMENT TO LABOUR CONTRACTORS",
                                "PAYMENT TO LABOUR CONTRACTORS",
                            ),
                            ("PAYMENT TO VEHICLE RENTAL", "PAYMENT TO VEHICLE RENTAL"),
                            ("ELECTRICITY CHARGES", "ELECTRICITY CHARGES"),
                            ("WATER CHARGES", "WATER CHARGES"),
                            (
                                "JOB WORK NOT BILLED/BOOKED YET",
                                "JOB WORK NOT BILLED/BOOKED YET",
                            ),
                            ("INSURANCE", "INSURANCE"),
                            ("TDS & TCS", "TDS & TCS"),
                            ("GST (MONTHLY RETURN)", "GST (MONTHLY RETURN)"),
                            ("CUSTOM DUTY + IGST", "CUSTOM DUTY + IGST"),
                            ("ADVANCE TAX", "ADVANCE TAX"),
                            ("INTEREST PAYMENTS", "INTEREST PAYMENTS"),
                            ("LOAN RE-PAYMENT", "LOAN RE-PAYMENT"),
                        ],
                        max_length=80,
                    ),
                ),
                ("due_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("remarks", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "manual_payable_entry",
                "ordering": ["-due_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PayablePartyExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("party_name", models.CharField(max_length=255)),
                (
                    "party_norm",
                    models.CharField(db_index=True, editable=False, max_length=255),
                ),
                (
                    "company_group",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("extend_days", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ACCOUNTS_payablepartyextension",
                "indexes": [
                    models.Index(
                        fields=["party_norm", "company_group", "active"],
                        name="ACCOUNTS_pa_party_n_2f64a0_idx",
                    )
                ],
            },
        ),
    ]
