# Generated by Django 5.0.11 on 2025-07-17 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("R_and_D", "0002_alter_r_and_d_moisture_product_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kffactorentry",
            name="analysed_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category": "Analyst"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="kf_entries_analysed",
                to="R_and_D.rdmaster",
            ),
        ),
        migrations.AlterField(
            model_name="r_and_d_moisture",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category": "Unit"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="moisture_units",
                to="R_and_D.rdmaster",
                verbose_name="Unit",
            ),
        ),
    ]
