# Generated by Django 5.0.11 on 2025-07-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("R_and_D", "0003_alter_kffactorentry_analysed_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="r_and_d_moisture",
            name="sample_weight_gm",
            field=models.DecimalField(
                decimal_places=5, max_digits=10, verbose_name="Sample Weight (gm)"
            ),
        ),
    ]
