# Generated by Django 5.0.11 on 2025-07-28 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("R_and_D", "0004_alter_r_and_d_moisture_sample_weight_gm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="r_and_d_moisture",
            name="moisture_percent",
        ),
        migrations.AddField(
            model_name="r_and_d_moisture",
            name="melting_point",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Melting Point (%)",
            ),
        ),
        migrations.AlterField(
            model_name="kffactorentry",
            name="analysed_by",
            field=models.ForeignKey(
                limit_choices_to={"category": "Analyst"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="kf_entries_analysed",
                to="R_and_D.rdmaster",
            ),
        ),
        migrations.AlterField(
            model_name="r_and_d_moisture",
            name="instrument",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category": "Instrument"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="moisture_instruments",
                to="R_and_D.rdmaster",
                verbose_name="Instrument",
            ),
        ),
        migrations.AlterField(
            model_name="r_and_d_moisture",
            name="product_name",
            field=models.CharField(max_length=100, verbose_name="Product N"),
        ),
        migrations.AlterField(
            model_name="r_and_d_moisture",
            name="sample_weight_gm",
            field=models.DecimalField(
                decimal_places=5, max_digits=10, verbose_name="Sample Weight (mg)"
            ),
        ),
    ]
