# Generated by Django 5.0.11 on 2025-07-28 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("R_and_D", "0005_remove_r_and_d_moisture_moisture_percent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="r_and_d_moisture",
            name="melting_point",
        ),
        migrations.AddField(
            model_name="r_and_d_moisture",
            name="moisture_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Moisture (%)",
            ),
        ),
        migrations.AlterField(
            model_name="kffactorentry",
            name="analysed_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category": "Analyst"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="kf_entries_analysed",
                to="R_and_D.rdmaster",
            ),
        ),
        migrations.AlterField(
            model_name="r_and_d_moisture",
            name="instrument",
            field=models.ForeignKey(
                limit_choices_to={"category": "Instrument"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="moisture_instruments",
                to="R_and_D.rdmaster",
                verbose_name="Instrument",
            ),
        ),
        migrations.AlterField(
            model_name="r_and_d_moisture",
            name="product_name",
            field=models.CharField(max_length=100, verbose_name="Product Name"),
        ),
    ]
