# Generated by Django 5.0.11 on 2025-07-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("R_and_D", "0006_remove_r_and_d_moisture_melting_point_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="r_and_d_moisture",
            name="moisture_percent",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Moisture (%)"
            ),
        ),
    ]
