# Generated by Django 5.0.11 on 2025-07-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("R_and_D", "0007_alter_r_and_d_moisture_moisture_percent"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeltingPointRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_date", models.DateField()),
                ("entry_time", models.TimeField()),
                ("eln_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("batch_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "sample_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("unit", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "instrument",
                    models.CharField(
                        blank=True,
                        choices=[("Lab India", "Lab India"), ("Veego", "Veego")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "melting_point",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Melting Point",
                    ),
                ),
                (
                    "analysed_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Completed Date"
                    ),
                ),
                (
                    "completed_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Completed Time"
                    ),
                ),
            ],
            options={
                "verbose_name": "Melting Point Record",
                "verbose_name_plural": "Melting Point Records",
                "db_table": "melting_point_record",
            },
        ),
    ]
