# Generated by Django 5.0.11 on 2025-10-13 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("R_and_D", "0008_meltingpointrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meltingpointrecord",
            name="melting_point",
            field=models.CharField(
                blank=True,
                help_text="e.g., 101-102 or 101.5",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_melting_point",
                        message="Enter a number or a range like 101-102 or 101.5-102.2",
                        regex="^\\s*\\d+(\\.\\d+)?(\\s*-\\s*\\d+(\\.\\d+)?)?\\s*$",
                    )
                ],
            ),
        ),
    ]
