# Generated by Django 5.0.11 on 2026-01-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DomesticETATracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PoNumber", models.CharField(max_length=50)),
                (
                    "Status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In Transit", "In Transit"),
                            ("Cleared", "Cleared"),
                            ("Rejection", "Rejection"),
                            ("Hold", "Hold"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "RequiredDate",
                    models.DateField(
                        blank=True, null=True, verbose_name="Required Date at Plant"
                    ),
                ),
                (
                    "ETDDate",
                    models.DateField(blank=True, null=True, verbose_name="ETD Date"),
                ),
                (
                    "RevisedETADate",
                    models.DateField(
                        blank=True, null=True, verbose_name="Revised ETA Date"
                    ),
                ),
                ("RawMaterial", models.CharField(max_length=255)),
                ("Packing", models.CharField(blank=True, max_length=100, null=True)),
                ("Qty", models.DecimalField(decimal_places=3, max_digits=12)),
                ("Supplier", models.CharField(max_length=255)),
                (
                    "LiftingLocation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "TransporterName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("VehicleNo", models.CharField(blank=True, max_length=50, null=True)),
                ("LRNo", models.CharField(blank=True, max_length=50, null=True)),
                ("DriverNo", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "Evaluation",
                    models.CharField(
                        blank=True,
                        choices=[("Safety", "Safety"), ("Service", "Service")],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("Photos", models.BinaryField(blank=True, max_length="max", null=True)),
                (
                    "InvoiceNoRemark",
                    models.CharField(
                        default="Pending",
                        max_length=255,
                        verbose_name="Invoice No / Remark",
                    ),
                ),
                ("InvoiceDate", models.DateField(blank=True, null=True)),
                ("Remark", models.CharField(blank=True, max_length=300, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Domestic ETA Tracking",
                "verbose_name_plural": "Domestic ETA Tracking",
                "db_table": "domestic_eta_tracking",
                "indexes": [
                    models.Index(
                        fields=["PoNumber"], name="domestic_et_PoNumbe_e8d62f_idx"
                    ),
                    models.Index(
                        fields=["Status"], name="domestic_et_Status_1a8262_idx"
                    ),
                    models.Index(
                        fields=["RequiredDate"], name="domestic_et_Require_caa21b_idx"
                    ),
                    models.Index(
                        fields=["Supplier"], name="domestic_et_Supplie_840b3d_idx"
                    ),
                    models.Index(
                        fields=["TransporterName"],
                        name="domestic_et_Transpo_0209fe_idx",
                    ),
                ],
            },
        ),
    ]
