# Generated by Django 5.0.11 on 2026-01-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DomesticETA", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domesticetatracking",
            name="Remark",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
