# Generated by Django 5.0.11 on 2026-02-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DomesticETA", "0002_alter_domesticetatracking_remark"),
    ]

    operations = [
        migrations.AddField(
            model_name="domesticetatracking",
            name="FreightCharges",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Freight Charges",
            ),
        ),
    ]
