# Generated by Django 5.0.11 on 2025-08-14 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ETP", "0004_productionschedule_productionscheduleline"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrimaryTreatmentEffluent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "effluent_nature",
                    models.CharField(
                        choices=[
                            ("Ejector effluent", "Ejector effluent"),
                            ("Outside Drainage Water", "Outside Drainage Water"),
                            (
                                "PCO Cleaning / cleaning Effluent",
                                "PCO Cleaning / cleaning Effluent",
                            ),
                            ("Scrubber Acidic Effluent", "Scrubber Acidic Effluent"),
                            ("Scrubber Basic Effluent", "Scrubber Basic Effluent"),
                            ("Spent HCL", "Spent HCL"),
                            ("Acidic", "Acidic"),
                            ("Acidic Aq. Layer", "Acidic Aq. Layer"),
                            ("Basic", "Basic"),
                            ("Nuetral", "Nuetral"),
                            ("Residue", "Residue"),
                            ("Sodium Cyanide Effluent", "Sodium Cyanide Effluent"),
                            (
                                "Sulphuric above 50% effluent",
                                "Sulphuric above 50% effluent",
                            ),
                            (
                                "Sulphuric below 50 % effluent",
                                "Sulphuric below 50 % effluent",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "effluent_received",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "effluent_neutralized",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
            options={
                "verbose_name": "Primary Treatment Effluent",
                "verbose_name_plural": "Primary Treatment Effluents",
                "db_table": "primary_treatment_effluent",
            },
        ),
        migrations.CreateModel(
            name="PrimaryTreatmentChemical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chemical_name", models.CharField(max_length=100)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "effluent_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chemicals_used",
                        to="ETP.primarytreatmenteffluent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Primary Treatment Chemical",
                "verbose_name_plural": "Primary Treatment Chemicals",
                "db_table": "primary_treatment_chemical",
            },
        ),
    ]
