# Generated by Django 5.0.11 on 2025-08-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ETP", "0005_primarytreatmenteffluent_primarytreatmentchemical"),
    ]

    operations = [
        migrations.AlterField(
            model_name="effluentrecord",
            name="product_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
