# Generated by Django 5.0.11 on 2025-10-13 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ETP", "0006_alter_effluentrecord_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="primarytreatmenteffluent",
            name="effluent_nature",
            field=models.CharField(
                choices=[
                    ("Scrubber Acidic Effluent", "Scrubber Acidic Effluent"),
                    ("Spent HCL", "Spent HCL"),
                    ("Acidic", "Acidic"),
                    ("Acidic Aq. Layer", "Acidic Aq. Layer"),
                    ("Basic", "Basic"),
                    ("Nuetral", "Nuetral"),
                    ("Residue", "Residue"),
                    ("Sodium Cyanide Effluent", "Sodium Cyanide Effluent"),
                    ("Sulphuric above 50% effluent", "Sulphuric above 50% effluent"),
                    ("Sulphuric below 50 % effluent", "Sulphuric below 50 % effluent"),
                ],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="HazardousWaste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Record date")),
                ("challan_no", models.CharField(max_length=50)),
                ("manifest_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "transporter_name",
                    models.CharField(
                        max_length=255, verbose_name="Name of the Transporter"
                    ),
                ),
                (
                    "vehicle_registration_numbers",
                    models.TextField(
                        help_text="Vehicle registration number(s). Use one per line if multiple.",
                        verbose_name="Vehicle Registration Number",
                    ),
                ),
                (
                    "type_of_waste",
                    models.TextField(
                        help_text="e.g., 20.3 Distillation Residues; 28.1 Process Residue and wastes"
                    ),
                ),
                (
                    "quantity_mt",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Quantity of Waste (MT)",
                    ),
                ),
                (
                    "disposal_rate_rs_per_mt",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Waste Disposal Rate (Rs/MT)",
                    ),
                ),
                (
                    "transportation_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "disposal_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pre-Processing", "Pre-Processing"),
                            ("Incineration", "Incineration"),
                            ("Land filling", "Land filling"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("disposal_facility", models.CharField(max_length=255)),
                (
                    "license_valid_upto",
                    models.DateField(
                        blank=True, null=True, verbose_name="License Validity (upto)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hazardous Waste",
                "verbose_name_plural": "Hazardous Waste",
                "db_table": "hazardous_waste",
                "indexes": [
                    models.Index(fields=["date"], name="hazardous_w_date_24e61d_idx"),
                    models.Index(
                        fields=["challan_no"], name="hazardous_w_challan_6e2933_idx"
                    ),
                    models.Index(
                        fields=["manifest_no"], name="hazardous_w_manifes_36b395_idx"
                    ),
                    models.Index(
                        fields=["transporter_name"],
                        name="hazardous_w_transpo_8372d9_idx",
                    ),
                ],
            },
        ),
    ]
