# Generated by Django 5.0.11 on 2025-10-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ETP", "0007_alter_primarytreatmenteffluent_effluent_nature_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hazardouswaste",
            name="waste_category",
            field=models.CharField(
                blank=True,
                help_text="e.g., 20.3 / 28.1 / 35.3",
                max_length=20,
                null=True,
            ),
        ),
    ]
