# Generated by Django 5.0.11 on 2025-10-24 06:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ETP", "0008_hazardouswaste_waste_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="EffluentTank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "capacity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
            options={
                "db_table": "effluent_tank",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EffluentOpeningBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.DateField(help_text="First day of month (YYYY-MM-01)"),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "tank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_balances",
                        to="ETP.effluenttank",
                    ),
                ),
            ],
            options={
                "db_table": "Effluent_opening_balance",
                "indexes": [
                    models.Index(
                        fields=["tank", "month"], name="Effluent_op_tank_id_c73f41_idx"
                    )
                ],
                "unique_together": {("tank", "month")},
            },
        ),
    ]
