# Generated by Django 5.0.11 on 2025-12-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ETP", "0009_effluenttank_effluentopeningbalance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hazardouswaste",
            name="disposal_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pre-Processing", "Pre-Processing"),
                    ("Incineration", "Incineration"),
                    ("Land filling", "Land filling"),
                    ("Recycle", "Recycle"),
                    ("Other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="primarytreatmenteffluent",
            name="effluent_nature",
            field=models.CharField(
                choices=[
                    ("Scrubber Acidic Effluent", "Scrubber Acidic Effluent"),
                    ("Spent HCL", "Spent HCL"),
                    ("Acidic", "Acidic"),
                    ("Acidic Aq. Layer", "Acidic Aq. Layer"),
                    ("Basic", "Basic"),
                    ("Residue", "Residue"),
                    ("Sodium Cyanide Effluent", "Sodium Cyanide Effluent"),
                    ("Sulphuric above 50% effluent", "Sulphuric above 50% effluent"),
                    ("Sulphuric below 50 % effluent", "Sulphuric below 50 % effluent"),
                ],
                max_length=100,
            ),
        ),
    ]
