# Generated by Django 5.0.11 on 2026-01-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ETP", "0010_alter_hazardouswaste_disposal_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hazardouswaste",
            name="disposal_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pre-Processing", "Pre-Processing"),
                    ("Incineration", "Incineration"),
                    ("Land filling", "Land filling"),
                    ("Recycle", "Recycle"),
                    ("For Further Treatment", "For Further Treatment"),
                    ("Other", "Other"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
